### PR TITLE
TINY-6086: Fixed a regression introduced in 5.3.0 whereby the `images_dataimg_filter` wouldn't ever be called

### LINKED ISSUE #5756: Broken "images_dataimg_filter" option (since 5.3.0)
[`images_dataimg_filter` option](https://www.tiny.cloud/docs/configure/file-image-upload/#images_dataimg_filter) was used to disable converting Base64 images into Blobs. In 5.3.0 there is a new algorithm replacing Base64 images with Blobs all time not respecting 
`images_dataimg_filter` option.

This change was related to #5557 (issue with Safari with too large Base64 images), but the lack of the option to avoid Blobs affects to TinyMCE in all browsers now.

If option `images_dataimg_filter` can not be used anymore, I suppose TinyMCE should provide some option like `disable_blobs` in order to provide ability to insert Base64 icons into the content.

### PR DESCRIPTION
**Pull request by lnewson**
Description of Changes:
This adds a fix to the new parser filter introduced in 5.3.0 that converts base64 images to blobs while parsing. With this change, if the `images_dataimg_filter` is configured an image element will be constructed and then passed to the callback to see if the image should be converted to a blob. If it returns false, then it'll leave it as base64 content.

This also fixes the `EditorUploadTest`, as it was very broken and wasn't failing when assertions failed previously.

**Note:** This is only a temporary fix to unblock the 5.3 enterprise release. We'll need to come back to this in a later release, as moving forward for RTC we need to avoid having base64 images in the editor (which is why this the new filter was introduced).

Pre-checks:
* [x] Changelog entry added
* [x] Tests have been added (if applicable)
* [x] Branch prefixed with `feature/` for new features (if applicable)
* [x] License headers added on new files (if applicable)

Review:
* [x] Milestone set
* [x] Review comments resolved

GitHub issues (if applicable):
* Fixes #5756

### CODE REVIEW

File: modules/tinymce/src/core/test/ts/browser/EditorUploadTest.ts [hunk 1]
```diff
@@ -18,6 +19,7 @@ UnitTest.asynctest('browser.tinymce.core.EditorUploadTest', (success, failure) =
   Theme();
 
   let testBlobDataUri;
+  let dataImgFilter: (img: HTMLImageElement) => boolean;
```
Comment (metricjs) [inline modules/tinymce/src/core/test/ts/browser/EditorUploadTest.ts:22]: A note, more than anything: when we write up all the caveats for when we revisit this, should make sure we note why this was necessary. And probably include a "please rewrite this as not a LegacyUnit test".
