### PR TITLE
TINY- 6229: Added live embed support for video and audio elements

### LINKED ISSUE #5540: Audio and video not displaying in editor
**What is the current behavior? Describe the bug**

When I try to insert a video or audio through insert -> media, it displays an image like so:
Screenshot 2020-03-28 at 20 20 10

It works on the example editor on the home page and I haven't configured the media plugin any differently to the default settings, so I'm not sure why it's not working.

I'm using Safari on macOS Catalina.

Thanks in advance.

### PR DESCRIPTION
**Pull request by lnewson**
Related Ticket: TINY-6229

Description of Changes:
* Added live embed support for video and audio elements
* Added support for resizing video/audio live embed media elements. These will use the transparent src for the ghost image, as showing the actual element has a number of negative impacts (eg autoplay, focus stealing, etc...).
  * **Note:** Audio is specifically excluded, as it doesn't support width/height attributes and generally doesn't make sense to have it resizable.
* Fixed a bug whereby the width/height styles on a media element would incorrectly get copied to the preview wrapper element

Pre-checks:
* [x] Changelog entry added
* [x] Tests have been added (if applicable)
* [x] Branch prefixed with `feature/` for new features (if applicable)
* [x] License headers added on new files (if applicable)

Review:
* [x] Milestone set
* [x] Review comments resolved

GitHub issues (if applicable):
Fixes #5540

### CODE REVIEW

File: modules/tinymce/src/core/main/ts/api/dom/ControlSelection.ts [hunk 1]
```diff
@@ -290,11 +314,19 @@ const ControlSelection = (selection: EditorSelection, editor: Editor): ControlSe
...
+            top: '0',
+            width: '100%',
+            height: '100%'
+          });
+
+          selectedElmGhost = createGhostElement(selectedElm);
           dom.addClass(selectedElmGhost, 'mce-clonedresizable');
           dom.setAttrib(selectedElmGhost, 'data-mce-bogus', 'all');
-          selectedElmGhost.contentEditable = false; // Hides IE move layer cursor
-          selectedElmGhost.unSelectabe = true;
```
Comment (lnewson) [inline modules/tinymce/src/core/main/ts/api/dom/ControlSelection.ts:297]: This had a typo, so it was doing nothing and `unselectable` isn't a valid property anymore (was in old IE versions) as such I just removed it.

**Review by JamesToohey — APPROVED** [review]

File: modules/tinymce/src/plugins/media/main/ts/core/Nodes.ts [hunk 2]
```diff
@@ -5,26 +5,65 @@
...
 
 declare let escape: any;
 
-const createPlaceholderNode = function (editor: Editor, node: AstNode) {
+const isLiveEmbedNode = (node: AstNode) => {
+  const name = node.name;
+  return name === 'iframe' || name === 'video' || name === 'audio';
+};
+
+const getDimension = (node: AstNode, styles: Record<string, string>, dimension: 'width' | 'height', defaultValue: string | null = null): string | null => {
```
Comment (ashfordneil) [inline modules/tinymce/src/plugins/media/main/ts/core/Nodes.ts:24]: Should some of these nulls be Optionals?

**Review by ashfordneil — APPROVED** [review]

File: modules/tinymce/src/plugins/media/main/ts/core/Nodes.ts (hunk 2 above)
Comment (lnewson) [reply modules/tinymce/src/plugins/media/main/ts/core/Nodes.ts:24]: They could be, but we'd just have to unwrap them anyways since we're working with the public TinyMCE `Node` API and it requires `null` values.

Comment (lnewson) [reply modules/tinymce/src/plugins/media/main/ts/core/Nodes.ts:24]: Another point worth mentioning, this is code being used for a node filter, so we generally try to avoid having to create unnecessary objects, function calls, etc... as it needs to be as performant as possible since content parsing happens a fair bit and can lead to bottlenecks (it's why core uses for loops instead of `Arr.each`).

**Review by metricjs — APPROVED** [review]
