### PR TITLE
TINY-3897 & TINY-6667: Fixed issues with fake table selection on Firefox

### LINKED ISSUE #4914: Merging two cells - issues in Firefox
**Do you want to request a *feature* or report a *bug*?**
This is possibly a bug with TinyMCE, possibly a bug with Firefox, but I thought it worth registering with you in case it's the former.

**What is the current behavior?**
When you drag across two cells in a table then try to merge them in Firefox, it doesn't work. If you drag across more than two, it does work, the look of the selection changing slightly. If you drag across more than two, then back to two, it works then as well.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Drag across two cells in Firefox and try to merge them as described above. I've reproduced this on the full featured example on your site.

**What is the expected behavior?**
That it would merge two cells without any extra dragging needed.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Firefox only as far as I know. I'm on Ubuntu, but I've had colleagues on other OSes reporting a similar issue.

### LINKED ISSUE #5078: Version 5.0.11 - Table bug - The second table cannot merge any cells
The second table cannot merge any cells. After selecting the merge option with a few cells in the second table, nothing happens and then the first table is automatically selected. Tested in the latest version of Firefox.

http://fiddle.tinymce.com/LMgaab

### PR DESCRIPTION
**Pull request by lnewson**
Related Ticket: TINY-3897 & TINY-6667

Description of Changes:
Fixes an issue with Firefox whereby the selection would be incorrect when selecting only 2 cells and then trying to do operations.

Note: I had tried preventing the mouseover, etc... events to try and stop Firefox changing the selection, but unfortunately nothing worked. Either way, it still makes sense to ensure the fake selection is correct on `mouseup` since we know that's the end point in the selection.

Pre-checks:
* [x] Changelog entry added
* [x] Tests have been added (if applicable)
* [x] ~Branch prefixed with `feature/` for new features (if applicable)~
* [x] ~License headers added on new files (if applicable)~

Review:
* [x] Milestone set
* [x] Review comments resolved

GitHub issues (if applicable):
Fixes #4914
Fixes #5078

### CODE REVIEW

File: modules/darwin/src/main/ts/ephox/darwin/mouse/MouseSelection.ts [hunk 1]
```diff
@@ -46,7 +39,23 @@ export const MouseSelection = (bridge: WindowBridge, container: SugarElement, is
...
+    findCell(event.target, isRoot).each(cursor.set);
+  };
+
+  /* Keep this as lightweight as possible when we're not in a table selection, it runs constantly */
+  const mouseover = (event: EventArgs<MouseEvent>) => {
+    applySelection(event);
+  };
+
+  /* Keep this as lightweight as possible when we're not in a table selection, it runs constantly */
+  const mouseup = (event?: EventArgs<MouseEvent>) => {
```
Comment (lnewson) [inline modules/darwin/src/main/ts/ephox/darwin/mouse/MouseSelection.ts:53]: I was wondering if we should make this event mandatory. Thoughts?

Comment (ashfordneil) [reply modules/darwin/src/main/ts/ephox/darwin/mouse/MouseSelection.ts:53]: I don't know why it would be not mandatory — but that probably means I'm missing the original reason (on account of me not knowing very much at all about this code)

File: modules/tinymce/changelog.txt [hunk 2]
```diff
@@ -14,6 +14,7 @@ Version 5.7.0 (TBD)
     Changed the type signature for `editor.selection.getRng()` incorrectly returning `null` #TINY-6843
     Changed some `SaxParser` regular expressions to improve performance #TINY-6823
     Fixed `col` elements incorrectly transformed to `th` elements when converting columns to header columns #TINY-6715
+    Fixed a number of table operations not working when selecting 2 table cells on Mozilla Firefox #TINY-3897
```
Comment (ashfordneil) [inline modules/tinymce/changelog.txt:17]: Do we normally refer to it as "Mozilla Firefox" in the docs?

File: modules/tinymce/src/plugins/table/test/ts/browser/TwoCellsSelectionTest.ts [hunk 3]
```diff
@@ -0,0 +1,113 @@
...
+      '</table>'
+    );
+    const path = colgroup ? [ 0, 1, 1, 1, 0 ] : [ 0, 0, 1, 1, 0 ];
+    TinySelections.setCursor(editor, path, 1);
+    const startCell = UiFinder.findIn(TinyDom.body(editor), 'td:contains(B2)').getOrDie();
+    const endCellSelector = direction === Direction.Column ? 'td:contains(B1)' : 'td:contains(A2)';
+    const endCell = UiFinder.findIn(TinyDom.body(editor), endCellSelector).getOrDie();
+
+    // Drag over the 2 cells to select them
+    Mouse.mouseDown(startCell);
```
Comment (ashfordneil) [inline modules/tinymce/src/plugins/table/test/ts/browser/TwoCellsSelectionTest.ts:39]: Is this the right order? Wouldn't it mouse-over first

**Review by ashfordneil — APPROVED** [review]

File: modules/tinymce/changelog.txt (hunk 2 above)
Comment (lnewson) [reply modules/tinymce/changelog.txt:17]: Style guide says to use the full product name, eg `Microsoft Internet Explorer`: https://www.tiny.cloud/docs/configure/contributing-docs/#usepropernamesforprogramsandlanguages

File: modules/darwin/src/main/ts/ephox/darwin/mouse/MouseSelection.ts (hunk 1 above)
Comment (lnewson) [reply modules/darwin/src/main/ts/ephox/darwin/mouse/MouseSelection.ts:53]: I suspect it just got incorrectly converted when adding types since it's not currently used in the function :shrug:

**Review by JamesToohey — APPROVED** [review]

**Review by ltrouton — APPROVED** [review]

**Review by HAFRMO — APPROVED** [review]

File: modules/tinymce/src/plugins/table/test/ts/browser/TwoCellsSelectionTest.ts (hunk 3 above)
Comment (lnewson) [reply modules/tinymce/src/plugins/table/test/ts/browser/TwoCellsSelectionTest.ts:40]: Have fixed this as discussed.

File: modules/darwin/src/main/ts/ephox/darwin/mouse/MouseSelection.ts (hunk 1 above)
Comment (lnewson) [reply modules/darwin/src/main/ts/ephox/darwin/mouse/MouseSelection.ts]: Have changed this to mandatory as discussed.
