### PR TITLE
TINY-6058: Fixed clicking on notifications causing inline editors to hide

### LINKED ISSUE #5702: Inline Paste Notification can't be closed in Firefox on OSX
**What is the current behavior? Describe the bug**
In inline mode with Firefox when I click 'Paste' (in menubar) a notification is shown. I can't close this notification because the editor gets closed (an the notification unvisible) when clicking the close button of the notification (when the notification gets the focus).

**Please provide the steps to reproduce and if possible a minimal demo of the problem**
* http://fiddle.tinymce.com/Ljhaab
* Activate editor by clicking the text
* Click 'Edit' in menubar
* Click 'Paste' (-> Notification to use keyboard shortcuts is shown)
* Try to close the notification

**What is the expected behavior?**
Interacting with the notification (closing, marking text) won't close the editor

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Tinymce 5.3.0 in Firefox 76.0.1 on OSX

### PR DESCRIPTION
**Pull request by lnewson**
Related Ticket: TINY-6058

Description of Changes:
This fixes an issue whereby clicking the notification would cause inline editors to hide, since the focus would move back to the body.

Pre-checks:
* [x] Changelog entry added
* [x] Tests have been added (if applicable)
* [x] ~Branch prefixed with `feature/` for new features (if applicable)~
* [x] ~License headers added on new files (if applicable)~

Review:
* [x] Milestone set
* [x] Review comments resolved

GitHub issues (if applicable):
Fixes #5702

### CODE REVIEW

File: modules/tinymce/src/themes/silver/main/ts/ui/general/Notification.ts [hunk 1]
```diff
@@ -144,24 +144,14 @@ const factory: UiSketcher.SingleSketchFactory<NotificationSketchDetail, Notifica
...
-      tag: 'div',
-      attributes: {
-        role: 'alert'
-      },
-      classes: detail.level.map((level) => [ 'tox-notification', 'tox-notification--in', `tox-notification--${level}` ]).getOr(
-        [ 'tox-notification', 'tox-notification--in' ]
-      )
-    },
-    components: [ {
+  const components: AlloySpec[] = [
```
Comment (lnewson) [inline modules/tinymce/src/themes/silver/main/ts/ui/general/Notification.ts:147]: I should add I pulled this out to remove the assertions done previously, which would have meant the specs weren't being typed checked.
