### PR TITLE
TINY-6940: Support mixed case files extensions when handling images

### LINKED ISSUE #6459: Can't upload images with uppercase extensions using image plugin
**Current behavior**
Can't upload files with uppercase extension (.JPG, .PNG) using image plugin. Image modal doesn't respond if file with uppecase extension is either dragged or selected in Image modal -> Upload tab.

Image plugin validates file type using extension (`images_file_types` setting was added #TINY-6224). By default only files ending with `jpeg,jpg,jpe,jfi,jif,jfif,png,gif,bmp,webp` (https://www.tiny.cloud/docs/configure/file-image-upload/#images_file_types) are allowed. Comparison is case-sensitive, presence of `jpg` in `images_file_types` does not white-list `.JPG` files.

**Steps to reproduce**
Try to upload file with .JPG extension on tinyMCE instance using image plugin with upload tab.
```
plugins: "image",
toolbar: "image",
images_upload_url: 'http://example.com/',
```

https://codepen.io/lwd8cmd/pen/wvzbGaj

**What is the expected behavior?**
Images with uppercase extensions (.JPG, ...) should be uploaded and displayed in TinyMCE edit area.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? **
Tested with TinyMCE 5.6.0.

**Possible solution**
Transform file extension to lowercase when retrieving image's MIME type in https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/plugins/paste/main/ts/core/Utils.ts#L150
```
+ ext = ext.toLowerCase();
```

### PR DESCRIPTION
**Pull request by JamesToohey**
Related Ticket:

TINY-6940

Description of Changes:

Fixed an issue introduced by TINY-6306 where capitalised file extensions were treated as invalid.

Pre-checks:
* [x] Changelog entry added
* [x] Tests have been added (if applicable)
* [x] ~~Branch prefixed with `feature/` for new features (if applicable)~~
* [x] ~~License headers added on new files (if applicable)~~

Review:
* [x] Milestone set
* [x] Review comments resolved

GitHub issues (if applicable):
Fixes #6459

### CODE REVIEW

**Review by ashfordneil — APPROVED** [review]

File: modules/tinymce/src/plugins/paste/main/ts/core/SmartPaste.ts [hunk 1]
```diff
@@ -33,7 +33,7 @@ const isAbsoluteUrl = (url: string) => {
 };
 
 const isImageUrl = (editor: Editor, url: string) => {
-  return isAbsoluteUrl(url) && Arr.exists(Settings.getAllowedImageFileTypes(editor), (type) => Strings.endsWith(url, `.${type}`));
+  return isAbsoluteUrl(url) && Arr.exists(Settings.getAllowedImageFileTypes(editor), (type) => Strings.endsWith(url.toLowerCase(), `.${type}`));
```
Comment (lnewson) [inline modules/tinymce/src/plugins/paste/main/ts/core/SmartPaste.ts:36]: We really want a proper case insensitive lookup here, so both `type` and `url` need to be converted to lowercase here.

- [ ] Ensure this is a proper case insensitive comparison

File: modules/tinymce/src/themes/silver/main/ts/ui/dialog/Dropzone.ts [hunk 2]
```diff
@@ -28,7 +28,7 @@ const defaultImageFileTypes = 'jpeg,jpg,jpe,jfi,jif,jfif,png,gif,bmp,webp';
 
 const filterByExtension = (files: FileList, providersBackstage: UiFactoryBackstageProviders) => {
   const allowedImageFileTypes = Tools.explode(providersBackstage.getSetting('images_file_types', defaultImageFileTypes, 'string'));
-  const isFileInAllowedTypes = (file: File) => Arr.exists(allowedImageFileTypes, (type) => Strings.endsWith(file.name, `.${type}`));
+  const isFileInAllowedTypes = (file: File) => Arr.exists(allowedImageFileTypes, (type) => Strings.endsWith(file.name.toLowerCase(), `.${type}`));
```
Comment (lnewson) [inline modules/tinymce/src/themes/silver/main/ts/ui/dialog/Dropzone.ts:31]: Also need to lowercase both `type` and `file.name` here as well.

**Review by lnewson — APPROVED** [review]
