### PR TITLE
TINY-4727: Inserting large base64 encoded images in Safari creates an empty `<img>` tag

### LINKED ISSUE #5425: Inserting large base64 encoded images in Safari creates an empty <img> tag.
On Safari, inserting a base64 encoded image via execCommand('mceInsertContent') creates an empty  tag when the  tag's string length exceeds 1,000,003 characters. In other words, when the image's base64 length is large. Below is an example:

http://fiddle.tinymce.com/pchaab

This affects all Safari versions and is due to a Safari bug. The following line in SaxParser.ts fails to parse the attributes associates with the  tag:

attribsValue.replace(attrRegExp, parseAttribute);

Safari fails to call parseAttribute() when attribsValue is larger than 1,000,003 characters.

### PR DESCRIPTION
**Pull request by spocke**
This fixes a github community bug but it's also something we need for RTC basically we want to avoid having base64 encoded attributes in the editor and let the scanner convert them to blobs. Instead this will convert everything upfront to blobs when content is inserted into the editor.

I also changed the DomParser and DomSerializer setups so they don't get the editor settings but instead a copy of the settings specific to those things this is something I have wanted to change for a long time but I had to separate out a bunch of mutating tests since mutating editor.settings will now no longer mutate DomParser or DomSerializer settings they are immutable copies.

Fixes #5425

### CODE REVIEW

**Comment by TheSpyder** [comment]
Fixes #5425

File: modules/tinymce/src/core/main/ts/api/html/DomParser.ts [hunk 1]
```diff
@@ -12,6 +12,10 @@ import Tools from '../util/Tools';
 import Node from './Node';
 import SaxParser from './SaxParser';
 import Schema from './Schema';
+import { BlobCache } from '../file/BlobCache';
+import { uniqueId } from '../../file/ImageScanner';
+import * as Conversions from '../../file/Conversions';
+import { buildBase64DataUri } from 'tinymce/core/html/Base64Uris';
```
Comment (lnewson) [inline modules/tinymce/src/core/main/ts/api/html/DomParser.ts]: This should be a relative import path, instead of an alias path.

- [ ] Fix import path

File: modules/tinymce/src/core/main/ts/api/html/SaxParser.ts [hunk 2]
```diff
@@ -71,6 +72,7 @@ export interface SaxParserSettings {
   pi? (name: string, text: string): void;
   start? (name: string, attrs: AttrList, empty: boolean): void;
   text? (text: string, raw?: boolean): void;
+  dataUri? (match: Base64UriMatch): string;
```
Comment (lnewson) [inline modules/tinymce/src/core/main/ts/api/html/SaxParser.ts]: This feels like it's an inconsistent/bad API, as it's really not anything a streaming API should be doing since all the return types should be `void` otherwise it's not streaming (all the other callbacks are return type is void). I think this would be better suited to being passed in as a setting to `SaxParser`, something like `resolve_data_uri` maybe? or even better being pre-processed by DomParser (see my other comment)?

- [ ] Reconsider making this a callback API as it doesn't fit the current API

File: modules/tinymce/src/core/main/ts/api/html/SaxParser.ts [hunk 3]
```diff
@@ -629,6 +629,18 @@ function SaxParser(settings?: SaxParserSettings, schema = Schema()): SaxParser {
...
+  /**
+   * Parses the specified HTML string and executes the callbacks for each item it finds.
+   *
+   * @example
+   * SaxParser({...}).parse('<b>text</b>');
+   * @method parse
+   * @param {String} html Html string to sax parse.
+   */
+  const parse = (html: string, format: ParserFormat = 'html') => {
+    parseHtml(extractBase64DataUris(html), format);
```
Comment (lnewson) [inline modules/tinymce/src/core/main/ts/api/html/SaxParser.ts]: Again, this doesn't look like it's really the right place for this sort of logic. The `SaxParser` is a streaming API, so I believe if we want to extract this, it should be done in `DomParser` instead before we pass it to the `SaxParser`, as that's more relevant to processing it into DOM elements.

File: modules/tinymce/src/core/main/ts/api/html/SaxParser.ts [hunk 4]
```diff
@@ -206,16 +208,10 @@ function SaxParser(settings?: SaxParserSettings, schema = Schema()): SaxParser {
...
-  /**
-   * Parses the specified HTML string and executes the callbacks for each item it finds.
-   *
-   * @example
-   * SaxParser({...}).parse('<b>text</b>');
-   * @method parse
-   * @param {String} html Html string to sax parse.
-   */
-  const parse = (html: string, format: ParserFormat = 'html') => {
+  const parseHtml = (base64Extract: Base64Extract, format: ParserFormat = 'html') => {
```
Comment (lnewson) [inline modules/tinymce/src/core/main/ts/api/html/SaxParser.ts]: This name isn't really appropriate, as this can parse HTML and XHTML (and technically it works as a lenient XML parser).

File: modules/tinymce/src/core/main/ts/html/Base64Uris.ts [hunk 5]
```diff
@@ -0,0 +1,63 @@
...
+}
+
+export interface Base64Extract {
+  prefix: string;
+  uris: Record<string, Base64UriMatch>;
+  html: string;
+}
+
+export const extractBase64DataUris = (html: string): Base64Extract => {
+  const dataImageUri = /data:(image\/[a-z]+);base64,([a-z0-9\+\/=]+)/gi;
```
Comment (lnewson) [inline modules/tinymce/src/core/main/ts/html/Base64Uris.ts]: This regex won't work for images that have a `+` in the mime type, eg: `image/svg+xml` or other valid types such as the ones listed here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#Image_types

- [ ] Ensure this works with mime types that have a plus, hyphen, etc...

File: modules/tinymce/src/core/main/ts/init/InitContentBody.ts [hunk 6]
```diff
@@ -50,8 +51,95 @@ const appendStyle = function (editor: Editor, text: string) {
...
+
+const removeUndefined = <T>(obj: T): T => {
+  return Obj.filter(obj as Record<string, unknown>, (v) => Type.isUndefined(v) === false) as T;
+};
+
+const mkParserSettings = (editor: Editor): DomParserSettings => {
+  const settings = editor.settings;
+  const blobCache = editor.editorUpload.blobCache;
+
+  return removeUndefined<DomParserSettings>({
```
Comment (lnewson) [inline modules/tinymce/src/core/main/ts/init/InitContentBody.ts]: Hmm, I don't really like that this just asserts the type, as settings could be missing. I'll try and see if theres a way we can do this without having to do the cast today.

File: modules/tinymce/src/core/main/ts/init/InitContentBody.ts [hunk 7]
```diff
@@ -50,8 +51,95 @@ const appendStyle = function (editor: Editor, text: string) {
...
+    root_name: getRootName(editor),
+    validate: true,
+    blob_cache: blobCache
+  });
+};
+
+const mkSerializerSettings = (editor: Editor): SerializerSettings => {
+  const settings = editor.settings;
+
+  return removeUndefined<SerializerSettings>({
```
Comment (lnewson) [inline modules/tinymce/src/core/main/ts/init/InitContentBody.ts]: Can this use the `mkParserSettings` to remove duplication, as serializer settings extend parser settings?

File: modules/tinymce/src/core/test/ts/atomic/html/Base64UrisTest.ts [hunk 8]
```diff
@@ -0,0 +1,134 @@
+import { Assert, UnitTest } from '@ephox/bedrock-client';
+import { extractBase64DataUris, Base64Extract, buildBase64DataUri, restoreDataUris, Base64UriMatch } from 'tinymce/core/html/Base64Uris';
+import { Obj } from '@ephox/katamari';
+import { Logger } from '@ephox/agar';
+
+UnitTest.test('Base64Uris Test', () => {
```
Comment (lnewson) [inline modules/tinymce/src/core/test/ts/atomic/html/Base64UrisTest.ts]: This doesn't follow the normal core/plugin test naming convention, does that matter? eg it's normally `atomic.tinymce.core.html.Base64UrisTest`

File: modules/tinymce/src/plugins/textpattern/test/ts/browser/TextPatternPluginForcedRootBlockFalseTest.ts [hunk 9]
```diff
@@ -0,0 +1,35 @@
+import {GeneralSteps, Pipeline, Step } from '@ephox/agar';
```
Comment (lnewson) [inline modules/tinymce/src/plugins/textpattern/test/ts/browser/TextPatternPluginForcedRootBlockFalseTest.ts]: Missing space here after `{`.

Switching to eslint would help us pick up on these automatically, but that's another days task 😛 

- [ ] Fix missing space

File: modules/tinymce/src/core/main/ts/html/Base64Uris.ts [hunk 10]
```diff
@@ -0,0 +1,63 @@
...
+  base64: string;
+}
+
+export interface Base64Extract {
+  prefix: string;
+  uris: Record<string, Base64UriMatch>;
+  html: string;
+}
+
+export const extractBase64DataUris = (html: string): Base64Extract => {
```
Comment (lnewson) [inline modules/tinymce/src/core/main/ts/html/Base64Uris.ts]: Another thing I just noticed, this name is very misleading, as it doesn't extract base64 data URIs and instead only extracts **image** base64 URIs.

- [ ] Consider renaming this, or make it work with all mime types, not just images.

File: modules/tinymce/src/core/main/ts/init/InitContentBody.ts (hunk 6 above)
Comment (lnewson) [reply modules/tinymce/src/core/main/ts/init/InitContentBody.ts]: Ignore sorry, I misread.

File: modules/tinymce/src/core/main/ts/api/html/SaxParser.ts (hunk 4 above)
Comment (spocke) [reply modules/tinymce/src/core/main/ts/api/html/SaxParser.ts]: Name suggestions? parseMarkup, doParse.

File: modules/tinymce/src/core/main/ts/api/html/SaxParser.ts (hunk 3 above)
Comment (spocke) [reply modules/tinymce/src/core/main/ts/api/html/SaxParser.ts]: That is not possible since the SaxParser is what is causing the bug with the backtracking. So we need to process away the huge blobs before we parse or it will fail.

File: modules/tinymce/src/core/main/ts/api/html/SaxParser.ts (hunk 4 above)
Comment (lnewson) [reply modules/tinymce/src/core/main/ts/api/html/SaxParser.ts]: `internalParse` maybe? otherwise either of those look good to me.

File: modules/tinymce/src/core/main/ts/init/InitContentBody.ts (hunk 7 above)
Comment (spocke) [reply modules/tinymce/src/core/main/ts/init/InitContentBody.ts]: I guess we could run that and merge the two objects. Saves a few bytes of code.

File: modules/tinymce/src/core/main/ts/api/html/SaxParser.ts (hunk 3 above)
Comment (lnewson) [reply modules/tinymce/src/core/main/ts/api/html/SaxParser.ts]: That's what I said though? As you'd preprocess it before using SaxParser, as atm it's trying to do that in a streaming API which isn't the right place, since it's concern is to just fire events/callback when encountering certain data.

File: modules/tinymce/src/core/test/ts/atomic/html/Base64UrisTest.ts (hunk 8 above)
Comment (spocke) [reply modules/tinymce/src/core/test/ts/atomic/html/Base64UrisTest.ts]: Not sure about the naming convention here I used to have the dot notation but some devs doesn't seem to follow that so everything is inconsistent now. The file name is reported as well as the test name so maybe it's not that important?

File: modules/tinymce/src/core/main/ts/api/html/SaxParser.ts (hunk 2 above)
Comment (spocke) [reply modules/tinymce/src/core/main/ts/api/html/SaxParser.ts]: Yes let's rename it to data_uri_resolver.

File: modules/tinymce/src/core/main/ts/api/html/DomParser.ts (hunk 1 above)
Comment (TheSpyder) [reply modules/tinymce/src/core/main/ts/api/html/DomParser.ts]: Why are aliases bad? I made sure they were configured in every `tsconfig.json` so they can be used where it makes sense 🤔

File: modules/tinymce/src/core/main/ts/api/html/SaxParser.ts (hunk 3 above)
Comment (lnewson) [reply modules/tinymce/src/core/main/ts/api/html/SaxParser.ts]: Looking at this, more this probably is okay as it just extracts the data uris and replaces it with tokens.

So it's really the `dataUris` callback that I don't like here, so how about instead we keep this but remove `dataUris` from `SaxParser`. Then we just replace the token with the actual URI when firing the `start` callback that contains the attribute list. From there we can then manipulate the URIs and convert them to blobs from within the `start` callback in DomParser. Thoughts?

Comment (spocke) [reply modules/tinymce/src/core/main/ts/api/html/SaxParser.ts]: Right I can rework this so it puts back the base64 url in the attribute callback then we can get rid of the dataUri callback but that would mean we would have to parse the dara url again in the DOMParser mime and data but that should be pretty fast.

Comment (spocke) [reply modules/tinymce/src/core/main/ts/api/html/SaxParser.ts]: On mobile didn't see you comment there we are on the same page.

**Comment by spocke** [comment]
I tested this code on Safari before I made the PR and it can parse a 2mb blob in 8ms so the regexp is fine it's the backtracking that isn't fine in the SaxParser.

File: modules/tinymce/src/core/main/ts/api/html/SaxParser.ts (hunk 3 above)
Comment (lnewson) [reply modules/tinymce/src/core/main/ts/api/html/SaxParser.ts]: Yeah, the performance and having to re-parse the mime type is a valid point. Maybe we should just instead go with making it a setting and calling it `data_uri_resolver` even if that does mix the concerns a bit 🤷‍♀ Your call on what you think is best 👍

File: modules/tinymce/src/core/main/ts/file/Conversions.ts [hunk 11]
```diff
@@ -64,27 +65,33 @@ const parseDataUri = function (uri: string) {
   };
 };
 
-const dataUriToBlob = function (uri: string): Promise<Blob> {
-  return new Promise(function (resolve) {
-    let str, arr, i;
+const buildBlob = (type: string, data: string): Option<Blob> => {
```
Comment (TheSpyder) [inline modules/tinymce/src/core/main/ts/file/Conversions.ts]: This is mostly duplicate with `imagetools` which was recombined into TinyMCE with the monorepo 🤔 
https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/core/main/ts/file/Conversions.ts#L67

File: modules/tinymce/src/core/test/ts/atomic/html/Base64UrisTest.ts (hunk 8 above)
Comment (lnewson) [reply modules/tinymce/src/core/test/ts/atomic/html/Base64UrisTest.ts]: Yeah, I'm not sure either. Most of the tests in `silver` don't follow this convention, but most other things do so I just thought I'd point it out. I'm not worried either way to be honest 👍

File: modules/tinymce/src/core/main/ts/api/html/DomParser.ts (hunk 1 above)
Comment (lnewson) [reply modules/tinymce/src/core/main/ts/api/html/DomParser.ts]: Because if you try and import this from somewhere else then it won't work, as TypeScript doesn't convert them to relative paths when it generates the JS, which leads to broken import paths.

Comment (lnewson) [reply modules/tinymce/src/core/main/ts/api/html/DomParser.ts]: Additionally, if we were to distribute the types, this would fail for anyone trying to use them since they'd also have to setup the aliases. So really aliases should really only be used in tests or the like, which aren't something that'd be packaged or consumed elsewhere.

Comment (TheSpyder) [reply modules/tinymce/src/core/main/ts/api/html/DomParser.ts]: Wasn't that only a problem when we published libraries, and even then not in the top-level editor project that doesn't publish as a library? It certainly shouldn't matter in the monorepo?

I admit I haven't checked, so if the aliases are pointless let's delete them so this becomes a compile error instead of a social concept. That will make the tests more annoying though.

Comment (lnewson) [reply modules/tinymce/src/core/main/ts/api/html/DomParser.ts]: As I said, it'll be an issue if we ever want to publish the types so we really shouldn't be doing it. You are right though that for tinymce specifically we only distribute the bundled JS, so the aliases aren't really an issue there (with the exception of harbinger).

I'd also be against removing the aliases, as otherwise in tests you just end up with a massive `../../../../../../` path since you need to traverse up a lot of directories. Most IDE's have a setting that allows you to only use the alias if it's outside the configured tsconfig paths so I'd suggest we make sure to configure that instead (not sure if VS code has that). As an example, for IntelliJ we have this setting:
image

Comment (lnewson) [reply modules/tinymce/src/core/main/ts/api/html/DomParser.ts]: I think there was some discussion at one stage about seeing if we could right a linter rule to stop these being used in inappropriate places. Maybe we should see if we can prioritise that? 🤷‍♀

Comment (TheSpyder) [reply modules/tinymce/src/core/main/ts/api/html/DomParser.ts]: I think we should blanket allow them in `modules/tinymce` - types we probably need a script processed solution for anyway - and find a way to disallow them in other parts of the monorepo (except for tests). We rely on aliases to, for example, map core references to `tinymce` global references in plugins.

https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/plugins/advlist/main/ts/Plugin.ts#L8

Either way we definitely need lint rules to enforce code style decisions like this. Also perhaps IDE configuration, if vscode does has a setting I'll resurrect my branch that adds a vscode workspace file and encourage the team to use it. We've made great use of that in RTC.

Comment (spocke) [reply modules/tinymce/src/core/main/ts/api/html/DomParser.ts]: I added a lint rules for general libraries a while back was harder to do for tiny so I didn't do that maybe it can be expanded. https://github.com/tinymce/tslint-rules/blob/master/src/test/rules/no-path-alias-imports/src/main/test.ts.lint

File: modules/tinymce/src/core/main/ts/file/Conversions.ts (hunk 11 above)
Comment (spocke) [reply modules/tinymce/src/core/main/ts/file/Conversions.ts]: Not sure I want to merge those in this PR but you are right there is code duplication here.

**Comment by spocke** [comment]
@lnewson Thanks for the feedback on this PR the changes worked out great it made the code far simpler and also more generic.

**Comment by lnewson** [comment]
> Thanks for the feedback on this PR the changes worked out great it made the code far simpler and also more generic.

Glad to hear and the changes look good, thanks for making those @spocke 👍
