### PR TITLE
TINY-8348: Fixed bugs from options conversion

### LINKED ISSUE #7458: [6.0.0-alpha.20211209] Tiny try to load a non existing file: "default"
**After init Tiny try to load a non existing file with name "default"**

[https://fiddle.tiny.cloud/YRhaab/1](https://fiddle.tiny.cloud/YRhaab/1)
and check Browser Debugger:

image

Browser: Chrome and Firefox
Tinymce Inline Mode [6.0.0-alpha.20211209]

Tiny <6.0.0 does not show this behavior

### PR DESCRIPTION
**Pull request by lnewson**
Related Ticket: TINY-8348

Description of Changes:
* Fixed 2 separate minor issues found with the options conversion that caused incorrect defaults in inline mode and on touch devices.

Pre-checks:
* [x] Changelog entry added
* [x] Tests have been added (if applicable) -  No tests for the resize default since we don't have a way to test that at this stage. I have manually tested it though.
* [x] Branch prefixed with `feature/` for new features (if applicable)

Review:
* [x] Milestone set
* [x] Review comments resolved

GitHub issues (if applicable):
Fixes #7458

### CODE REVIEW

**Review by spocke — APPROVED** [review]

**Review by metricjs — APPROVED** [review]

File: modules/tinymce/src/themes/silver/main/ts/api/Options.ts [hunk 1]
```diff
@@ -266,7 +266,8 @@ const register = (editor: Editor): void => {
   registerOption('resize', {
     processor: (value) => value === 'both' || Type.isBoolean(value),
     // TODO: TINY-8288 - This should be set to `true` once the issue with the theme rendering too early is resolved
-    default: !editor.hasPlugin('autoresize')
+    // Editor resize doesn't work on touch devices at this stage
+    default: !Env.deviceType.isTouch() && !editor.hasPlugin('autoresize')
```
Comment (TheSpyder) [inline modules/tinymce/src/themes/silver/main/ts/api/Options.ts:270]: this doesn't seem related? 🤔

**Review by ashfordneil — APPROVED** [review]

**Review by TheSpyder — APPROVED** [review]
