### PR TITLE
TINY-4001: Cleanup attributes created on target element

### LINKED ISSUE #5117: TinyMCE doesn't cleanup after itself properly after remove()-ing the instance
**What is the current behavior? Describe the bug**

when using inline mode, tinymce modifies the element given by the selector in subtle ways, and after destroying the instance, it doesn't remove said modifications

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

http://fiddle.tinymce.com/VOgaab

instead of logging `<div id="test">just an inline-editable thing</div>` to the console, it logs `<div id="test" aria-hidden="true" style="">just an inline-editable thing</div>`

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE: 5.0.13
Chrome: Version 76.0.3809.100 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by ashfordneil**
Related Ticket:

Description of Changes:
Cleans up attributes on the target element when the editor is removed. Takes a snapshot of the attribute state when creating the editor, and restores it later. Also centralises a bit of code that was scattered around the codebase aiming to do the same thing for individual attributes / classes.

Pre-checks:
* [x] Changelog entry added
* [x] Tests have been added (if applicable)
* [x] Branch prefixed with `feature/` for new features (if applicable)
* [x] License headers added on new files (if applicable)

Review:
* [x] Milestone set
* [x] Review comments resolved

GitHub issues (if applicable):
Fixes #5117

### CODE REVIEW

File: modules/tinymce/src/core/main/ts/api/EditorManager.ts [hunk 1]
```diff
@@ -490,10 +490,19 @@ const EditorManager: EditorManager = {
     const initEditors = function () {
       let initCount = 0;
       const editors = [];
-      let targets: Element[];
+      let targets: HTMLElement[];
+
+      const createEditor = function (id: string, settings: RawEditorSettings, targetElm: HTMLElement) {
+        const targetElmWrap = SugarElement.fromDom(targetElm);
```
Comment (lnewson) [inline modules/tinymce/src/core/main/ts/api/EditorManager.ts:496]: This logic won't work if someone manually creates an editor (which I've seen Joomla and others do). As such it probably needs to be in the `Editor` itself, not in the `EditorManager`.

File: modules/tinymce/src/core/main/ts/api/EditorManager.ts [hunk 2]
```diff
@@ -373,19 +374,18 @@ const EditorManager: EditorManager = {
...
+      settings.inline && elm.tagName.toLowerCase() in invalidInlineTargets;
 
-    const createId = function (elm) {
+    const createId = function (elm: HTMLElement) {
       let id = elm.id;
 
       // Use element id, or unique name or generate a unique id
       if (!id) {
-        id = elm.name;
+        id = (elm as unknown as HTMLTextAreaElement).name as string | undefined;
```
Comment (lnewson) [inline modules/tinymce/src/core/main/ts/api/EditorManager.ts:385]: This is almost definitely the wrong type, as there are multiple elements this could be that have a `name` attribute.

Comment (lnewson) [reply modules/tinymce/src/core/main/ts/api/EditorManager.ts:385]: I suspect the best solution here would be to change the `elm` type to `elm: HTMLElement & { name?: string }`

File: modules/tinymce/src/core/main/ts/api/EditorManager.ts [hunk 3]
```diff
@@ -490,10 +490,19 @@ const EditorManager: EditorManager = {
...
+      let targets: HTMLElement[];
+
+      const createEditor = function (id: string, settings: RawEditorSettings, targetElm: HTMLElement) {
+        const targetElmWrap = SugarElement.fromDom(targetElm);
+        const tagSnapshot = Attr.clone(targetElmWrap);
 
-      const createEditor = function (id, settings, targetElm) {
         const editor: Editor = new Editor(id, settings, self);
+        editor.on('remove', () => {
+          Arr.each(Arr.map(targetElm.attributes, (attr) => attr.name), (name: string) => {
```
Comment (lnewson) [inline modules/tinymce/src/core/main/ts/api/EditorManager.ts:501]: This is looping twice when it's not needed. Additionally, the string type is not needed here/is an unnecessary type. So this could be simplified to this:
```
Arr.each(targetElm.attributes, (attr) => {
  Attr.remove(targetElmWrap, attr.name);
});
```

File: modules/tinymce/src/core/test/ts/browser/EditorCleanupTest.ts [hunk 4]
```diff
@@ -0,0 +1,47 @@
...
+import { UnitTest } from '@ephox/bedrock-client';
+import { Attr, Element, Truncate } from '@ephox/sugar';
+import { HTMLDivElement } from '@ephox/dom-globals';
+
+import Editor from 'tinymce/core/api/Editor';
+import { RawEditorSettings } from 'tinymce/core/api/SettingsTypes';
+import Theme from 'tinymce/themes/silver/Theme';
+import VisualBlocksPlugin from 'tinymce/plugins/visualblocks/Plugin';
+
+UnitTest.asynctest('browser.tinymce.core.EditorCleanupTest', (success, failure) => {
```
Comment (lnewson) [inline modules/tinymce/src/core/test/ts/browser/EditorCleanupTest.ts:12]: No tests here really check that the attributes are preserved, as you're always almost always just using an empty div with no attributes. The one exception is the `placeholder` attribute, but it'd be good to test other things like style, data attributes, etc...

File: modules/tinymce/src/core/test/ts/browser/EditorCleanupTest.ts [hunk 5]
```diff
@@ -0,0 +1,47 @@
...
+  Theme();
+  VisualBlocksPlugin();
+
+  const base_url = '/project/tinymce/js/tinymce';
+
+  const cTestCleanup = (settings: RawEditorSettings, html: string = '<div></div>') => NamedChain.asChain([
+    NamedChain.direct(NamedChain.inputName(), McEditor.cFromHtml(html, settings), 'editor'),
```
Comment (lnewson) [inline modules/tinymce/src/core/test/ts/browser/EditorCleanupTest.ts:19]: This line can be simplified to `NamedChain.write('editor', McEditor.cFromHtml(html, settings))`

File: modules/tinymce/src/core/test/ts/browser/EditorCleanupTest.ts [hunk 6]
```diff
@@ -0,0 +1,47 @@
...
+    NamedChain.direct('editor', Chain.mapper((editor: Editor) => Element.fromDom(editor.getElement())), 'element'),
+    NamedChain.read('editor', Chain.op((editor: Editor) => editor.remove())),
+    // first, remove the id of the element, as that's inserted from McEditor.cFromHtml and is out of our control
+    NamedChain.read('element', Chain.op((element: Element<HTMLDivElement>) => Attr.remove(element, 'id'))),
+    NamedChain.direct('element', Chain.mapper(Truncate.getHtml), 'raw-html'),
+    NamedChain.read('raw-html', Assertions.cAssertHtml('all properties on the element should be cleaned up', html)),
+    NamedChain.read('editor', McEditor.cRemove)
```
Comment (lnewson) [inline modules/tinymce/src/core/test/ts/browser/EditorCleanupTest.ts:26]: This won't work, as it relies on looking up the element based on the id that you removed above. Ideally, you should just call this above instead of `editor.remove()`.

File: modules/tinymce/src/core/test/ts/browser/EditorCleanupTest.ts [hunk 7]
```diff
@@ -0,0 +1,47 @@
...
+  ]);
+
+  Pipeline.async({}, [
+    Log.chainsAsStep('TINY-4001', 'Inline editor should clean up attributes', [
+      cTestCleanup({ base_url, inline: true })
```
Comment (lnewson) [inline modules/tinymce/src/core/test/ts/browser/EditorCleanupTest.ts:31]: Base URL is always needed here, so you could move this into the `cTestCleanup` function. eg:
```
NamedChain.write('editor', McEditor.cFromHtml(html, { base_url, ...settings }))
```

File: modules/tinymce/src/core/main/ts/api/EditorManager.ts [hunk 8]
```diff
@@ -373,19 +374,18 @@ const EditorManager: EditorManager = {
...
       let id = elm.id;
 
       // Use element id, or unique name or generate a unique id
       if (!id) {
-        id = elm.name;
+        id = (elm as unknown as HTMLTextAreaElement).name as string | undefined;
 
         if (id && !DOM.get(id)) {
-          id = elm.name;
+          // Keep current name
```
Comment (lnewson) [inline modules/tinymce/src/core/main/ts/api/EditorManager.ts:388]: This could also be improved to remove the empty block. eg:
```
if (!id || DOM.get(id)) {
  // Generate unique name
  id = DOM.uniqueId();
}
```

File: modules/tinymce/src/core/main/ts/api/EditorManager.ts (hunk 2 above)
Comment (lnewson) [reply modules/tinymce/src/core/main/ts/api/EditorManager.ts:385]: Another option, which would likely be even better, would be to do something like this:
```
id = Obj.get(elm, 'name').filter((name) => !DOM.get(id)).getOrThunk(DOM.uniqueId);
```

File: modules/tinymce/src/core/main/ts/api/EditorManager.ts (hunk 8 above)
Comment (lnewson) [reply modules/tinymce/src/core/main/ts/api/EditorManager.ts:388]: Another option, which would potentially be even better, would be to do something like this:
```
id = Obj.get(elm, 'name').filter((name) => !DOM.get(name)).getOrThunk(DOM.uniqueId);
```

File: modules/tinymce/src/core/main/ts/api/EditorManager.ts (hunk 3 above)
Comment (ashfordneil) [reply modules/tinymce/src/core/main/ts/api/EditorManager.ts:501]: Looping twice is needed so that we don't end up modifying the `attributes` list while mid-way through iterating through it*. That being said, I can rewrite it to make it more explicit that that's why the code is how it is.

*It was originally written the way that you have it there, and it'd bug out with some of the attributes in the list being `undefined` by the time the code got to them.

Comment (lnewson) [reply modules/tinymce/src/core/main/ts/api/EditorManager.ts:501]: That's not needed though, but you are correct about mutating the attributes being an issue. To solve that, you just need to loop backwards over the list, so you'd need to swap `each` to `eachr`.

Comment (ashfordneil) [reply modules/tinymce/src/core/main/ts/api/EditorManager.ts:501]: Change of plan I'm using `eachr` because that exists

File: modules/tinymce/src/core/test/ts/browser/EditorCleanupTest.ts (hunk 6 above)
Comment (ashfordneil) [reply modules/tinymce/src/core/test/ts/browser/EditorCleanupTest.ts:26]: For some reason that fix leaves the element that I'm testing with on the screen. I've swapped `McEditor.cRemove` for `Chain.op(Remove.remove)` on that last line and that's fixed the bug

Comment (lnewson) [reply modules/tinymce/src/core/test/ts/browser/EditorCleanupTest.ts]: As discussed on slack, this works but would be better if we stick to using the `McEditor.cRemove` chain. Reason being there's normally additional content that should be cleaned up, since TinyMCE doesn't do that atm (eg stylesheets). In saying that though, McEditor seems to not be doing that which is a bug.

Here's an example of what worked:
```
  const cTestCleanup = (settings: RawEditorSettings, html: string = '<div></div>') => NamedChain.asChain([
    // spin the editor up and down, getting a reference to its target element inbetween
    NamedChain.write('editor', McEditor.cFromHtml(html, { base_url: '/project/tinymce/js/tinymce', ...settings })),
    NamedChain.direct('editor', Chain.mapper((editor: Editor) => Element.fromDom(editor.getElement())), 'element'),
    NamedChain.read('editor', McEditor.cRemove),
    // first, remove the id of the element, as that's inserted from McEditor.cFromHtml and is out of our control
    NamedChain.read('element', Chain.op((element: Element<HTMLDivElement>) => Attr.remove(element, 'id'))),
    // assert that the html of the element is correct
    NamedChain.direct('element', Chain.mapper(Truncate.getHtml), 'raw-html'),
    NamedChain.read('raw-html', Assertions.cAssertHtml('all properties on the element should be cleaned up', html))
  ]);
```

File: modules/tinymce/src/core/test/ts/browser/EditorCleanupTest.ts [hunk 9]
```diff
@@ -0,0 +1,55 @@
...
+import { RawEditorSettings } from 'tinymce/core/api/SettingsTypes';
+import Theme from 'tinymce/themes/silver/Theme';
+import VisualBlocksPlugin from 'tinymce/plugins/visualblocks/Plugin';
+
+UnitTest.asynctest('browser.tinymce.core.EditorCleanupTest', (success, failure) => {
+  Theme();
+  VisualBlocksPlugin();
+
+  const cTestCleanup = (settings: RawEditorSettings, html: string = '<div></div>') => NamedChain.asChain([
+    // spin the editor up and down, getting a reference to its target element inbetween
```
Comment (lnewson) [inline modules/tinymce/src/core/test/ts/browser/EditorCleanupTest.ts:17]: Typo here (missing space or hypen at the end)

File: modules/tinymce/src/core/test/ts/browser/EditorCleanupTest.ts [hunk 10]
```diff
@@ -0,0 +1,55 @@
...
+    Log.chainsAsStep('TINY-4001', 'Inline editor should clean up attributes', [
+      cTestCleanup({ inline: true })
+    ]),
+
+    Log.chainsAsStep('TINY-4001', 'Iframe editor should clean up attributes', [
+      cTestCleanup({ })
+    ]),
+
+    Log.chainsAsStep('TINY-4001', 'Editor should replace existing attributes on teardown', [
+      cTestCleanup({ }, '<div classname="these are some classes"></div>'),
```
Comment (lnewson) [inline modules/tinymce/src/core/test/ts/browser/EditorCleanupTest.ts:40]: This should probably be `class` I imagine, instead of `classname`?

Comment (ashfordneil) [reply modules/tinymce/src/core/test/ts/browser/EditorCleanupTest.ts:40]: Yeah it should, that's my inner react programmer coming out.
