### PR TITLE
TINY-4709: Fixed formats incorrectly applied or removed when table cells were selected

### LINKED ISSUE #5408: Not removing multiple formats at the same time when selecting the table cells
**What is the current behavior?**
I'm creating a shortcut to highlight the text.
When the DOM already has a highlighted text, if the user is trying to add another one, it needs to remove the previous highlighted text and apply to the another selected text.
**The problem is**: when I already have a highlighted text and select the table cells applying the style, it does not remove the styled applied to the previous text.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14) or similar.**
tiny

**here is my code**: https://codesandbox.io/s/tinymce-sv49z

**What is the expected behavior?**
When selecting the table cells and applying the style, it should remove the previous highlighted text and apply only to the text in the table cells.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**
tiny 5.1.1

### PR DESCRIPTION
**Pull request by lnewson**
Having the fake selection walking logic in `RangeWalk` wasn't really the right place, as it needed to be when getting the ranges from the selection as that's what the fake selection is actually emulating (eg multi range selection). So this fixes a few things: it fixes the original issue and also removing formats from a fake table selection, as that didn't work (found this out when writing tests).

Fixes #5408

### CODE REVIEW

File: modules/tinymce/src/core/main/ts/selection/SelectionUtils.ts [hunk 1]
```diff
@@ -110,8 +115,34 @@ const hasAnyRanges = (editor: Editor) => {
   return sel && sel.rangeCount > 0;
 };
 
+const runOnRanges = (editor: Editor, executor: (rng: Range, fake: boolean) => void) => {
```
Comment (metricjs) [inline modules/tinymce/src/core/main/ts/selection/SelectionUtils.ts:118]: Is this just intended for Formatter styles or also table styles? Thinking of how some things like border/colours can be applied to to tds, trs, etc. Idk what getCellsFromEditor returns but I assume tds from the name, so wondered if it might miss some things/needs a comment to say what this does and doesn't apply to?

Comment (lnewson) [reply modules/tinymce/src/core/main/ts/selection/SelectionUtils.ts:118]: Discussed on slack. There was some confusion about what this does, so I've added a comment to clarify.
