### PR TITLE
TINY-5991: Fixed zero-width spaces incorrectly included in the `wordcount` plugin character count

### LINKED ISSUE #5659: On Bold,Italics,Underline select under toolbar section,char count(wordCount plugin) updated to 1 even when no text present
When editor is empty -> select the Bold from toolbar and check char count, its updated to 1 whereas it should update when user starts typing.

Tinymce 5.2.1.

I want to know if this is an expected behaviour because logically there is no character so it should return zero.

### PR DESCRIPTION
**Pull request by lnewson**
This strips zero-width spaces when fetching the text-based content from the editor, as they aren't visible and will normally be a fake caret, so they shouldn't be included in the character count.

Fixes #5659

### CODE REVIEW

File: modules/tinymce/src/plugins/wordcount/main/ts/core/GetText.ts [hunk 1]
```diff
@@ -5,25 +5,26 @@
  * For commercial licenses see https://www.tiny.cloud/
  */
 
-import { CharacterData, Node } from '@ephox/dom-globals';
+import { Node, Text } from '@ephox/dom-globals';
+import { Unicode } from '@ephox/katamari';
 import TreeWalker from 'tinymce/core/api/dom/TreeWalker';
 import Schema, { SchemaMap } from 'tinymce/core/api/html/Schema';
 
+const trimZwsp = (text: string) => text.replace(new RegExp(Unicode.zeroWidth, 'g'), '');
```
Comment (TheSpyder) [inline modules/tinymce/src/plugins/wordcount/main/ts/core/GetText.ts:13]: 🤔
https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/core/main/ts/text/Zwsp.ts#L24

Comment (lnewson) [reply modules/tinymce/src/plugins/wordcount/main/ts/core/GetText.ts:13]: Can't use that! It's in the internal API, but yes that's where I copied it from.

Comment (TheSpyder) [reply modules/tinymce/src/plugins/wordcount/main/ts/core/GetText.ts:13]: I realise you can't access it at runtime, and this isn't a common thing in our plugins, but could you link to it and let the rollup copy it in for you? 🤔

Comment (lnewson) [reply modules/tinymce/src/plugins/wordcount/main/ts/core/GetText.ts:13]: Rollup is configured to block anything outside the `api` module directory, to prevent it accidentally being used. So that fails as well unfortunately.

Comment (lnewson) [reply modules/tinymce/src/plugins/wordcount/main/ts/core/GetText.ts:13]: https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/Gruntfile.js#L102 for reference.

Comment (TheSpyder) [reply modules/tinymce/src/plugins/wordcount/main/ts/core/GetText.ts:13]: right, as I was writing it I figured one of us might have made it impossible to pull internal dependencies by accident

Maybe move `zwsp` to katamari? 😂

Comment (lnewson) [reply modules/tinymce/src/plugins/wordcount/main/ts/core/GetText.ts:13]: So you can use types from anywhere, but actual code can only be used from the `api` directory.

Comment (lnewson) [reply modules/tinymce/src/plugins/wordcount/main/ts/core/GetText.ts:13]: Dang GitHub not showing updated comments again :frowning: Yeah, that's feasible, so will look into that.
