### PR TITLE
TINY-5971 Valid Custom Element Names Can Now Contain a Wider Range of Characters

### LINKED ISSUE #3280: Incorrect RegExp in AddValidChildren method (childRuleRegExp)
One can find in the TinyMCE docs that custom elements are supported.
However TinyMCE does not support valid names of custom elements. In particular, there is a bug in this RegExp: `var childRuleRegExp = /^([+\-]?)(\w+)\[([^\]]+)\]$/;` because `\w` is equivalent to the `[A-Za-z0-9_]`. As a result the valid custom element name (which has to contain dash "-") will not be matched.

Rules of valid custom element name can be found in the following spec: https://www.w3.org/TR/custom-elements/#valid-custom-element-name

PS. In the same method `addValidChildren` the following line is redundant
`parent = children[matches[2]];`

### PR DESCRIPTION
**Pull request by trevorjay**
We currently allow users to add custom elements to the editor's element schema. However, the names supported have been anglocentric and--confusingly--not been compatible with the W3C's "custom element" schema. This patch broadens unicode and symbol support within names. For code points under 64k, names are now compatible with the last W3C "custom element" standard (before it was merged into the DOM standard). Code points above 64k are still not supported within names.

Related Ticket:

[TINY-5971](https://ephocks.atlassian.net/browse/TINY-5971)

Description of Changes:
* extends the `childRuleRegExp` regular expression used to check for valid children of custom elements

Pre-checks:
* [x] Changelog entry added
* [x] Tests have been added (if applicable)
* [x] ~~Branch prefixed with `feature/` for new features (if applicable)~~
* [x] ~~License headers added on new files (if applicable)~~

Review:
* [x] Milestone set
* [x] Review comments resolved

GitHub issues (if applicable):

Resolves #3280

### CODE REVIEW

File: modules/tinymce/src/core/main/ts/api/html/Schema.ts [hunk 1]
```diff
@@ -703,7 +703,7 @@ function Schema(settings?: SchemaSettings): Schema {
 
   // Adds valid children to the schema object
   const addValidChildren = function (validChildren) {
-    const childRuleRegExp = /^([+\-]?)(\w+)\[([^\]]+)\]$/;
+    const childRuleRegExp = /^([+\-]?)([A-Sa-z0-9_\-\.\u00b7\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u037d\u037f-\u1fff\u200c-\u200d\u203f-\u2040\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd]+)\[([^\]]+)\]$/; // from w3c's custom element grammar
```
Comment (lnewson) [inline modules/tinymce/src/core/main/ts/api/html/Schema.ts:706]: There's almost definitely a bug here, as `A-S` should be `A-Z`. We probably need a test for this to make sure it doesn't regress in future.

File: modules/tinymce/changelog.txt [hunk 2]
```diff
@@ -16,6 +16,7 @@ Version 5.4.0 (TBD)
     Changed stylesheet loading, so that UI skin stylesheets now to load in a ShadowRoot, if the editor is in a ShadowRoot. #TINY-6089
     Changed the DOM location of menus so that they display correctly when the editor is in a ShadowRoot. #TINY-6093
     Changed the table plugin to correctly detect all valid header row structures #TINY-6007
+    Changed custom element handling to support a broader set of names #5971
```
Comment (lnewson) [inline modules/tinymce/changelog.txt:19]: This shouldn't be `Changed`, it should either be `Added` or `Fixed`. Given we already support custom elements, this should probably be `Fixed`. Additionally, this is a little too broad of a statement as this is just fixing the ability to set the valid children for custom elements.

File: modules/tinymce/changelog.txt [hunk 3]
```diff
@@ -30,6 +30,7 @@ Version 5.4.0 (TBD)
     Fixed the `autolink` feature so that it no longer treats a string with multiple "@" characters as an email address #TINY-4773
     Fixed an issue where removing the editor would leave unexpected attributes on the target element #TINY-4001
     Fixed the `link` plugin now suggest `mailto:` when the text contains an '@' without URL separators (/'s) #TINY-5941
+    Fixed valid custom element names can now contain a wider range of characters #5971
```
Comment (lnewson) [inline modules/tinymce/changelog.txt:33]: This is missing `TINY-` in the number and this comment is still far too broad. TinyMCE has always allowed the full range for custom elements, it's only the single `valid_children` setting it didn't work for. So this should just refer to that.

File: modules/tinymce/src/core/main/ts/api/html/Schema.ts [hunk 4]
```diff
@@ -703,7 +703,7 @@ function Schema(settings?: SchemaSettings): Schema {
 
   // Adds valid children to the schema object
   const addValidChildren = function (validChildren) {
-    const childRuleRegExp = /^([+\-]?)(\w+)\[([^\]]+)\]$/;
+    const childRuleRegExp = /^([+\-]?)([A-Za-z0-9_\-\.\u00b7\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u037d\u037f-\u1fff\u200c-\u200d\u203f-\u2040\u2070-\u218f\u2c00-\u2fef\u3001-\ud7ff\uf900-\ufdcf\ufdf0-\ufffd]+)\[([^\]]+)\]$/; // from w3c's custom element grammar
```
Comment (lnewson) [inline modules/tinymce/src/core/main/ts/api/html/Schema.ts:706]: It might be good to include a link to the w3c spec maybe? eg `// from w3c's custom element grammar https://html.spec.whatwg.org/#valid-custom-element-name`

Comment (trevorjay) [reply modules/tinymce/src/core/main/ts/api/html/Schema.ts]: Yup. Added.

File: modules/tinymce/changelog.txt (hunk 3 above)
Comment (trevorjay) [reply modules/tinymce/changelog.txt]: I was approaching it from the angle that if not every codepath/use supported it then it's not supported (or is supported with caveats), but I totally see what you mean. Changing and adding the TINY-.

Comment (lnewson) [reply modules/tinymce/changelog.txt]: Looks good, thanks! :+1:

File: modules/tinymce/changelog.txt [hunk 5]
```diff
@@ -30,6 +30,7 @@ Version 5.4.0 (TBD)
     Fixed the `autolink` feature so that it no longer treats a string with multiple "@" characters as an email address #TINY-4773
     Fixed an issue where removing the editor would leave unexpected attributes on the target element #TINY-4001
     Fixed the `link` plugin now suggest `mailto:` when the text contains an '@' without URL separators (/'s) #TINY-5941
+    Fixed the `valid_children` check of custom elements now allows a wider range of characters in names #TINY-5971
```
Comment (tylerkelly13) [inline modules/tinymce/changelog.txt:33]: please s/ now allows / to allow /

Comment (trevorjay) [reply modules/tinymce/changelog.txt:33]: Done.
