### PR TITLE
TINY-3438: Fixed the editor selection incorrectly changing when removing caret format containers

### LINKED ISSUE #4875: Selection bug
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If i type one part of word as default format and other part with bold, when i start to select editor will select full word
screencast-www tiny cloud-2019 03 05-10-44-02

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
https://www.tiny.cloud/docs/demo/full-featured/

**What is the expected behavior?**
Editor must not change my selection

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
4.* 5.*

### PR DESCRIPTION
**Pull request by lnewson**
The logic that was trying to restore the selection offsets here was happening after the range had already been mutated and then unwrapped the node, which caused the range to change again. So this just stores the offsets before mutating the dom and restores it how it was previously attempting to after doing the dom mutation.

Fixes #4875

### CODE REVIEW

File: modules/tinymce/src/core/main/ts/fmt/CaretFormat.ts [hunk 1]
```diff
@@ -100,18 +100,25 @@ const removeCaretContainerNode = (editor: Editor, node: Node, moveCaret: boolean
   } else {
     const rng = selection.getRng();
     const block = dom.getParent(node, dom.isBlock);
+
+    // Store the current selection offsets
+    const startContainer = rng.startContainer;
+    const startOffset = rng.startOffset;
+    const endContainer = rng.endContainer;
+    const endOffset = rng.endOffset;
```
Comment (TheSpyder) [inline modules/tinymce/src/core/main/ts/fmt/CaretFormat.ts:108]: This is a big reason TBIO generally relies on a data structure with these four range details, not the range itself. Perhaps we should introduce that to TinyMCE (not now, later) as there are likely other places it will help 🤔
