### PR TITLE
TINY-7099: Ensure that error message is displayed in image upload dialog

### LINKED ISSUE #6579: problem with failure callback
I am trying to implement file upload using `images_upload_handler`. I faced an issue with handling errors when upload fails. I can't customize a title in the error dialog despite calling `failure("my_string_message")`. Calling failure("my_string_message")` shows a dialog with `[object Object]` in the title.

**What is the current behavior?**
Dialog with title `[object Object]`appears when file upload fails.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14) or similar.**
https://codepen.io/olyakolesnichenko/pen/QWGrRgE

**What is the expected behavior?**
A title from failure callback is expected

### PR DESCRIPTION
**Pull request by ashfordneil**
Related Ticket: TINY-7099

Description of Changes:
* Fix a regression where the error message stopped being displayed correctly in the image upload dialog (was just `[object Object]`)

Pre-checks:
* [x] Changelog entry added
* [x] Tests have been added (if applicable)
* ~[ ] Branch prefixed with `feature/` for new features (if applicable)~
* ~[ ] License headers added on new files (if applicable)~

Review:
* [x] Milestone set
* [x] Review comments resolved

GitHub issues (if applicable):
Fixes #6579

### CODE REVIEW

File: modules/tinymce/src/plugins/image/test/ts/browser/UploadTabTest.ts [hunk 1]
```diff
@@ -148,9 +148,11 @@ describe('browser.tinymce.plugins.image.ImagePluginTest', () => {
     TinyUiActions.clickOnUi(editor, '.tox-tab:contains("Upload")');
     await pTriggerUpload(editor);
     await TinyUiActions.pWaitForUi(editor, '.tox-alert-dialog');
+    // TINY-7099: Ensure that the correct error message is displayed
+    UiFinder.exists(SugarBody.body(), '.tox-alert-dialog .tox-dialog__body-content:contains("Error occurred")');
     TinyUiActions.clickOnUi(editor, '.tox-alert-dialog .tox-button:contains("OK")');
-    UiFinder.sNotExists(SugarBody.body(), '.tox-alert-dialog');
-    UiFinder.sExists(SugarBody.body(), '.tox-dialog__body-nav-item--active:contains("Upload")');
+    UiFinder.notExists(SugarBody.body(), '.tox-alert-dialog');
```
Comment (lnewson) [inline modules/tinymce/src/plugins/image/test/ts/browser/UploadTabTest.ts:154]: :facepalm: I must have missed these in the initial conversion. Thanks for fixing them!

**Review by lnewson — APPROVED** [review]

**Review by ltrouton — APPROVED** [review]
