### PR TITLE
TINY-3854: Fixed handling of mixed-case icon names by having the silver theme downcase them before icon retrieval

### LINKED ISSUE #5059: Problem with adding icons with capital letters
Icons display a bomb icon instead of loading the correct icon.  See issue #4887 as it still seems to be a problem in 5.0.9

So I create the file:
<base url>/icons/custom/icons.js:

tinymce.IconManager.add('custom', {
  icons: {
     'myCustomIcon': '<svg>...</svg>'
  }
});

Init code:
tinymce.init({
  ...
  icons: 'custom'
});

When you do the addButton operation in a plugin the icon is not displayed. No errors are shown in the console.
tinymce.PluginManager.add('adbplugins', function(editor, url) {
	editor.ui.registry.addButton('customButton', {
		tooltip: 'A sample custom button',
		icon: 'myCustomIcon',
		onAction: function(buttonApi) { /* some code */}
	});

I have only tested on 5.0.9.

### PR DESCRIPTION
**Pull request by trevorjay**
This PR fixes an issue with mixed-case icon names. Currently, icon names are downcased before entry into the registry. However, the `icon` key of a UI element (e.g. a button ) specification is not. This means that consistent capitalisation on the part of the user can lead to missing icons in the interface. Take this excerpt from [http://fiddle.tinymce.com/ILgaab/1](http://fiddle.tinymce.com/ILgaab/1) as an example:

    tinymce.IconManager.add('custom', {
      icons: {
        myCustomIcon: '<svg width="24" height="24"><circle cx="12" cy="12" r="10" stroke="green" stroke-width="4" fill="yellow" /></svg>'
      }
    });
    
    tinymce.PluginManager.add('adbplugins', function(editor, url) {
      editor.ui.registry.addButton('customButton', {
        tooltip: 'A sample custom button',
        icon: 'myCustomIcon',
        onAction: function(buttonApi) { }
      });
    });

Here, the user consistently refers to "myCustomIcon" in both the icon and button definitions. The icon name will be automatically downcased and the reference in the button definition won't be. Thus when the time comes to use the button definition to retrieve an icon, none will be found. There won't be any "myCustomIcon" icon in the registry, only a "mycustomicon" icon.

My fix is a short filter on "icon" key names when adding specifications to the registry. 

    const add = (collection, type: string) => (name: string, spec: any): void => collection[name.toLowerCase()] = { ...(() => {if (spec.icon !== undefined) {spec.icon = spec.icon.toLowerCase();};return spec;})(), type };

instead of:

    const add = (collection, type: string) => (name: string, spec: any): void => collection[name.toLowerCase()] = { ...spec, type };

I hate to use such ugly syntax, but I did not want to add a Katamari dependency to Registry.ts.

My understanding is that this needs to be handled at the registry level because user written themes retrieve both UI elements and `iconPack`s and *then* handle the mappings between elements and icons themselves. Our own silver theme does this, for example. Thus the names need to be made consistent as they sit in the registry.

This PR should resolve #5059.

### CODE REVIEW

File: modules/bridge/src/main/ts/ephox/bridge/api/Registry.ts [hunk 1]
```diff
@@ -49,7 +49,7 @@ export const create = (): Registry => {
   const contextMenus: Record<string, ContextMenuApi> = {};
   const contextToolbars: Record<string, ContextToolbarApi | ContextFormApi> = {};
   const sidebars: Record<string, SidebarApi> = {};
-  const add = (collection, type: string) => (name: string, spec: any): void => collection[name.toLowerCase()] = { ...spec, type };
+  const add = (collection, type: string) => (name: string, spec: any): void => collection[name.toLowerCase()] = { ...(() => {if (spec.icon !== undefined) {spec.icon = spec.icon.toLowerCase();};return spec;})(), type };
```
Comment (lnewson) [inline modules/bridge/src/main/ts/ephox/bridge/api/Registry.ts:52]: This isn't a great place to be doing this, as it's manipulating the spec. This should probably be fixed in `modules/tinymce/src/themes/silver/main/ts/ui/icons/Icons.ts` instead.

A couple other things just for future reference:
- This really needs some formatting (we seem to have lost this rule when moving to eslint as well)
- You're mutating the spec, which is something we avoid at all costs. If you need to edit this, clone it and make a new object instead.

Comment (lnewson) [reply modules/bridge/src/main/ts/ephox/bridge/api/Registry.ts:52]: Also, this should really have at least one test added to make sure we don't accidentally break this in future.

Comment (trevorjay) [reply modules/bridge/src/main/ts/ephox/bridge/api/Registry.ts:52]: I thought silver was just our canonical theme? It is a better place to add the fix but wouldn't that put the responsibility on anyone who writes their own theme to do the same?

Comment (lnewson) [reply modules/bridge/src/main/ts/ephox/bridge/api/Registry.ts:52]: It is, but it's the part where the bug really lies. As there are many other icons that are used that don't go via specs, so it cannot be done in the registry.

Comment (lnewson) [reply modules/bridge/src/main/ts/ephox/bridge/api/Registry.ts:52]: Ideally, that icon lookup code should really be in core (registry perhaps) rather than the theme, to similar.

Comment (trevorjay) [reply modules/bridge/src/main/ts/ephox/bridge/api/Registry.ts:52]: Per the discussion in Slack, I'll revamp this PR to be a quick fix to the silver theme and open a new issue for a bigger/longer-term fix that we can triage later.

Comment (trevorjay) [reply modules/bridge/src/main/ts/ephox/bridge/api/Registry.ts]: I've added the quickfix to all of the icon retrieval methods and added a test to `IconsTest`. I had to alter `AlertBannerTest` because its mock icon collection used a mixed case. Of course, it isn't (and hasn't) been possible to add mixed case icon names to the registry but `AlertBannerTest` manually constructed its collection for testing purposes.

**Comment by trevorjay** [comment]
The `continuous-integration/jenkins/branch` is failing for `win10IE-1` and `win10IE-3`. Both are reporting "ssh executable not found" as their error. I'm pretty confident my changes aren't responsible for that. Hopefully it's just a transient issue. I'll try rebuilding during work hours tomorrow and if the issue persist contact the service desk.

**Comment by trevorjay** [comment]
Build issue was unrelated to the code and is now resolved. Merging.
