### PR TITLE
TINY-4706/TINY-6273: Fixed an issue where link urls couldn't be deleted or edited in some cases

### LINKED ISSUE #4939: Hyperlinks changes do not apply if URL and text to display are the same
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When url and text to display in hyperlink are different, it is not possible to make them back the same.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Screen record provided: https://www.loom.com/share/78fe8e62080d409c89beccde66726647

**What is the expected behavior?**
It should be possible to change the "URL" value to the same as a "text to display" value 

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Issue exists in the tinymce fiddle.

### LINKED ISSUE #5403: Empty address field on link edit on image
Can't empty address field on link edit if link placed on image. But all works if link on text.

timymce Version 5.1.6, 5.2.0

delete link from image:
http://fiddle.tinymce.com/Bbhaab

### LINKED ISSUE #5888: Problem with erasing full url link when link has an img inside it
So, if I have an image inside an ```<a href>``` , trying to use the link toolbar button to edit/insert the image link and trying to erase the entire URL doesn't work( as soon as I erase the last character, the entire URL pops back into the input).

You can try it yourself by copy and pasting this code inside a TinyMCE editor:
```
<a href="https://www.popgateway.com/uTsaFD8MlleG5z4MorIRyC9FJ0jUk4FYUHeeItSzb2A2gJ30tFpuaNpjvprK6fLsJIGdHs3ZxWZkEYVZgrsC8g~~///"><img src="http://www.metta.org.uk/travel/images/mist2.jpg" alt="" /></a></p>
```
After that, try to click on the image and hit the edit link toolbar button. Then try to erase the entire url and see that you can't because it simply pops back.

### PR DESCRIPTION
**Pull request by lnewson**
Related Ticket: TINY-4706 & TINY-6273

Description of Changes:
* This fixes an issue where link urls couldn't be deleted/edited in the dialog. The cause was that we were incorrectly setting the URL "text" metadata which then made the typeahead component believe it was the same as the original url and replaced it with the original url.
* This also fixes another issue reported in one of the linked GitHub issues, that I also later found a JIRA for, in that the title was being incorrectly changed when changing the url.

Pre-checks:
* [x] Changelog entry added
* [x] Tests have been added (if applicable)
* [x] ~Branch prefixed with `feature/` for new features (if applicable)~
* [x] ~License headers added on new files (if applicable)~

Review:
* [x] Milestone set
* [x] Review comments resolved

GitHub issues (if applicable):
Fixes #4939
Fixes #5403
Fixes #5888

### CODE REVIEW

File: modules/tinymce/src/plugins/link/main/ts/ui/Dialog.ts [hunk 1]
```diff
@@ -58,28 +58,28 @@ const collectData = (editor): Promise<LinkDialogInfo> => {
...
-      original: {
-        value: info.anchor.url.getOr('')
+const getInitialData = (info: LinkDialogInfo, defaultTarget: Option<string>): LinkDialogData => {
+  const anchor = info.anchor;
+  const url = anchor.url.getOr('');
+
+  return {
+    url: {
+      value: url,
+      meta: {
```
Comment (metricjs) [inline modules/tinymce/src/plugins/link/main/ts/ui/Dialog.ts:68]: I don't quite remember how this data is meant to work for the urlinput, but I assume you've tested that this change doesn't break that functionality?

The old code also looks very odd to me, and now I'm wondering if we have similar anywhere else...

Comment (lnewson) [reply modules/tinymce/src/plugins/link/main/ts/ui/Dialog.ts:68]: Yeah, the data is just used as metadata for the typeahead popup. It's used to match if the URL data has both available, but we only ever store the URL in local storage so it's not meaningful and just causes other issues.

To be honest there's likely a separate issue with the whole Alloy dataset representing logic, but this solves the more immediate issue.
