### PR TITLE
TINY-6284: Make fullscreen mode request browser fullscreen

### LINKED ISSUE #4969: Add native fullscreen support
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
When tinymce container element gets into native browser fullscreen mode, menus do not appear when trying to open them.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Menus do not appear because they are appended not to tinymce root container, but to body. So they are simply not visible when root container is in fullscreen mode. I wrote a simplified fullscreen native plugin, demonstrating that:
```javascript
tinymce.PluginManager.add('nativefullscreen', function (editor) {
  
  editor.ui.registry.addButton('nativefullscreen', {
    icon: 'fullscreen',
    tooltip: 'Fullscreen',
    onAction: () => {
      const container = editor.getContainer();
      const requestFullscreen = container.requestFullscreen || container.mozRequestFullScreen;

      requestFullscreen.call(container);
    }
  });
});
```

**What is the expected behavior?**
Menus correctly appear in native fullscreen mode.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TineMCE 4/5, all browsers.

### PR DESCRIPTION
**Pull request by tiny-james**
Related Ticket: TINY-6284

Description of Changes:
* Allow the fullscreen plugin to actually trigger the fullscreen mode of the browser when setting `fullscreen_native` is set to `true`.

Pre-checks:
* [x] Changelog entry added
* [x] Tests have been added (if applicable)
* [x] Branch prefixed with `feature/` for new features (if applicable)
* [x] License headers added on new files (if applicable)

Review:
* [x] Milestone set
* [x] Review comments resolved

GitHub issues (if applicable):
Fixes #4969

### CODE REVIEW

File: modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts [hunk 1]
```diff
@@ -134,8 +168,13 @@ const toggleFullscreen = (editor: Editor, fullscreenState: Cell<any>) => {
     editor.on('remove', cleanup);
 
     fullscreenState.set(newFullScreenInfo);
+    fullscreenRoot.dom.requestFullscreen();
```
Comment (lnewson) [inline modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts:171]: I believe this won't work on IE or Safari as according to MDN and caniuse these are only exposed via the namespaces variants (eg `webkitRequestFullscreen()` and `msRequestFullscreen()`). I haven't verified, but just noting in case you haven't checked. It also applies to the othe fullscreen APIs.

Comment (lnewson) [reply modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts:171]: Also worth noting caniuse says full screen can't be activated by keydown or pointerdown. That will likely complicate things.

**Comment by lnewson** [comment]
As for a test, maybe you could just verify the fullscreenElement is set/not set when enabling/disabling? I can't think of much better sorry.

File: modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts (hunk 1 above)
Comment (tiny-james) [reply modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts:171]: Yep, I'll need to do some testing on IE but you are right that I will need a guard here.

The key command seems to work on Firefox as long as you don't spam it on and off multiple times but I guess Safari could have gone another way there.

**Comment by tiny-james** [comment]
> As for a test, maybe you could just verify the fullscreenElement is set/not set when enabling/disabling? I can't think of much better sorry.

Sounds like a good idea.

File: modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts (hunk 1 above)
Comment (lnewson) [reply modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts:171]: It may even be worthwhile to create a Sugar module to handle going fullscreen/closing fullscreen to handle the browser differences.

Comment (lnewson) [reply modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts]: Another thing, you can't add a guard here. If it's added to TinyMCE, then it'll need to work on all supported browsers for something like this.

Comment (tiny-james) [reply modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts]: Well it adds to the existing fullscreen mode so all the browsers have the original fullscreen (they fill the browser window, just not the monitor) as a fallback when the requestFullscreen() function is not available.

Comment (lnewson) [reply modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts]: This will need to be a setting to enable this, not change the current behaviour. So given it's an entire new feature it should work on all, especially since the other browsers do support it.

Comment (lnewson) [reply modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts]: If you disagree with the above, then please ask in slack, as that's where that'll need to be discussed and it'll need PM input if it's going to work differently on different browsers.

Comment (tiny-james) [reply modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts]: I don't disagree. I assumed it would need to be off by default as it is very obviously different behavior.
There is a slack discussion here:
https://jointiny.slack.com/archives/C0HUC9Y4D/p1596418866055300

Comment (lnewson) [reply modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts]: Yeah, I agree it'd need to be off by default. Even when it's enabled though, the editor normally needs to try and behave the same on all supported browsers. If that's not the case, then we'd need to make sure it's okay (hence the PM input) and document the limitation of the setting.

Comment (tiny-james) [reply modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts]: I got it working in IE now. In theory it should work in old Edge and old Safari too (though I can't test it myself).

Comment (tiny-james) [reply modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts]: The main difference between browsers now is the behaviour on the keyboard shortcut Ctrl+Shift+f as some browsers accept it as a valid trigger for fullscreen (but they rate limit it) and some ignore it completely so only the CSS fullscreen gets triggered.

File: modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts [hunk 2]
```diff
@@ -79,13 +94,70 @@ const viewportUpdate = WindowVisualViewport.get().fold(
   }
 );
 
-const toggleFullscreen = (editor: Editor, fullscreenState: Cell<any>) => {
+const getFullscreenRoot = (editor: Editor): SugarElement<Element> => {
```
Comment (lnewson) [inline modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts:97]: Could you move this fullscreen logic to its own module please (eg `NativeFullscreen.ts` or similar)? It'll just make it a little cleaner.

File: modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts [hunk 3]
```diff
@@ -79,13 +94,70 @@ const viewportUpdate = WindowVisualViewport.get().fold(
...
+    return (root as any).webkitFullscreenElement;
+  } else {
+    return null;
+  }
+};
+
+const getFullscreenchangeEventName = () => {
+  if (document.fullscreenElement !== undefined) {
+    return 'fullscreenchange';
+  }
```
Comment (lnewson) [inline modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts:118]: Why have the else on a new line, as that's not the normal codestyle we use? If there's no reason could you please collapse it to keep things consistent?

File: modules/tinymce/src/plugins/fullscreen/test/ts/webdriver/FullscreenPluginNativeModeTest.ts [hunk 4]
```diff
@@ -0,0 +1,68 @@
...
+
+  const cSetupEditor = McEditor.cFromSettings({
+    plugins: 'fullscreen',
+    toolbar: 'fullscreen',
+    theme: 'silver',
+    base_url: '/project/tinymce/js/tinymce',
+    fullscreen_native: true
+  });
+
+  const getFullscreenElement = () => {
```
Comment (lnewson) [inline modules/tinymce/src/plugins/fullscreen/test/ts/webdriver/FullscreenPluginNativeModeTest.ts:20]: If the fullscreen logic was moved to a separate module, you could maybe reuse the logic here instead of duplicating it?

File: modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts (hunk 3 above)
Comment (tiny-james) [reply modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts:118]: Sorry, that was because I was commenting/uncommenting things when I was trying to get IE working. I forgot to fix it.

File: modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts (hunk 2 above)
Comment (tiny-james) [reply modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts:97]: Sure

File: modules/tinymce/src/plugins/fullscreen/test/ts/webdriver/FullscreenPluginNativeModeTest.ts (hunk 4 above)
Comment (tiny-james) [reply modules/tinymce/src/plugins/fullscreen/test/ts/webdriver/FullscreenPluginNativeModeTest.ts:20]: Will do. Do you think we need any of it in Sugar?

Comment (lnewson) [reply modules/tinymce/src/plugins/fullscreen/test/ts/webdriver/FullscreenPluginNativeModeTest.ts:20]: I'm honestly not sure, so go with whatever you feel it best? 🤷

Comment (tiny-james) [reply modules/tinymce/src/plugins/fullscreen/test/ts/webdriver/FullscreenPluginNativeModeTest.ts:20]: It's probably pretty specific to the fullscreen plugin so I'll leave it there for now. I guess if we discover that the logic is useful elsewhere we can move it.

File: modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts [hunk 5]
```diff
@@ -79,13 +94,70 @@ const viewportUpdate = WindowVisualViewport.get().fold(
...
 
-const toggleFullscreen = (editor: Editor, fullscreenState: Cell<any>) => {
+const getFullscreenRoot = (editor: Editor): SugarElement<Element> => {
+  const elem = SugarElement.fromDom(editor.getElement());
+  return SugarShadowDom.getShadowRoot(elem).map(SugarShadowDom.getShadowHost).
+    getOrThunk(() => SugarBody.getBody(Traverse.owner(elem)));
+};
+
+const getFullscreenElement = (root: DocumentOrShadowRoot) => {
+  if (root.fullscreenElement !== undefined) {
```
Comment (ashfordneil) [inline modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts]: Would it be worth defining types for these, rather than using any? Something like this:

```ts
interface NativeFullscreen {
  fullscreenElement: Element;
  requestFullscreen: () => void;
  exitFullscreen: () => void;
}

interface MsFullscreen {
  msFullscreenElement: Element;
  msRequestFullscreen: () => void;
  ...
}

...

type Fullscreen = NativeFullscreen | MsFullscreen | ...

const isNative = (fs: Fullscreen): fs is NativeFullscreen = Obj.has(fs, 'fullscreenElement');
...
```

It's a bit more verbose, but you'd be able to replace all of the `(root as any)` instances with a single `(root as any as Fullscreen)`, after which point typescript would be able to track all of the types throughout the plugin.

Short of doing that, could we add explicit return types to these functions like `getFullscreenElement`, as otherwise the `any` will propagate through things.

File: modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts [hunk 6]
```diff
@@ -105,17 +177,29 @@ const toggleFullscreen = (editor: Editor, fullscreenState: Cell<any>) => {
     DOM.removeClass(editorContainer, 'tox-fullscreen');
 
     viewportUpdate.unbind();
+    Optional.from(fullscreenState.get()).each((info) => info.fullscreenChangeHandler.unbind());
```
Comment (ashfordneil) [inline modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts:125]: Why not just make fullscreenState either a `Cell<Optional<ScrollInfo>>` or a `Singleton.Value<ScrollInfo>`?

File: modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts (hunk 5 above)
Comment (lnewson) [reply modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts]: You're really not getting anything from doing that though... it saves one check. If you were to do this, you'd be better casting the element instead. eg:

```
interface FullscreenElement extends Element. {
  msFullscreenElement?: Element;
  msRequestFullscreen?: () => void;
  webkitFullscreenElement?: Element;
  webkitRequestFullScreen?: () => void;
}
```

Comment (lnewson) [reply modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts]: Worth noting though historically we've gone with the `any` approach for browser specific prefixes like this.

File: modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts (hunk 2 above)
Comment (lnewson) [reply modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts]: Thanks!

File: modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts (hunk 5 above)
Comment (tiny-james) [reply modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts]: You can also override the interface directly to add items (we sometimes do that for Window for globals we add). So it would become:
```
interface DocumentOrShadowRoot {
msFullscreenElement?: Element;
webkitFullscreenElement?: Element;
msExitFullscreen?: () => void;
webkitCancelFullScreen?: () => void;
}
interface Element {
msRequestFullscreen?: () => void;
webkitRequestFullScreen?: () => void;
}
```
https://www.typescriptlang.org/docs/handbook/declaration-merging.html

Comment (tiny-james) [reply modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts]: Hmm, doesn't seem to work. Nevermind.

File: modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts (hunk 6 above)
Comment (tiny-james) [reply modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts:125]: I did originally start converting to Singleton.Value but then I realized that it doesn't really have a good way of dealing with the toggling. Essentially for the toggle you have to do:
```
if (!singleton.isSet()) {
  singleton.set({
    // ...
  });
} else {
  singleton.on((value) => {
    // ....
   singleton.clear();
  });
}
```
So I decided that the code was actually clearer as it was.

File: modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts (hunk 5 above)
Comment (tiny-james) [reply modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts]: I have annotated the return types on all the functions.

Comment (tiny-james) [reply modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts]: I had another go at the declaration merging and this works:
```
declare global {
  interface DocumentOrShadowRoot {
    msFullscreenElement?: Element | null;
    webkitFullscreenElement?: Element | null;
  }
  interface Document {
    msExitFullscreen?: () => void;
    webkitCancelFullScreen?: () => void;
  }
  interface Element {
    msRequestFullscreen?: () => void;
    webkitRequestFullScreen?: () => void;
  }
}
```
Note that the change in the types seems to extend outside the file (which I didn't expect). So we may not want this. Should I leave it as is?

Comment (lnewson) [reply modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts]: Yeah, I thought that's what you'd have to do to get declaration merging working. I'd vote to not do that, because as you said it changes the global types, not just in this file.

File: modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts (hunk 6 above)
Comment (lnewson) [reply modules/tinymce/src/plugins/fullscreen/main/ts/core/Actions.ts:125]: One way we could do it, is if we used an option instead of a singleton, we could break the enable/disable logic out into separate functions and then use fold to branch. That, however, is really outside the scope of this PR.
