### PR TITLE
TINY-4592: Fixed toolbar buttons not set to disabled when the editor is in readonly mode

### LINKED ISSUE #5356: Readonly property not always working
**What is the current behavior? Describe the bug**
I really don't know what's going on here. 

1. Load tinymce with readonly config and display some toolbar tools (otherwise the problem won't be visible)
2. Sometimes, but only sometimes the buttons are disabled, sometimes not. To reproduce this you have to click the run button in the tinymce fiddle or reload the page. In the fiddle i get this bug about half of the times I load the page, in my project it's about 90% of the time. If you have e.g. bullet points in the toolbar you can also format text, which should definitely not happen.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/KZgaab

**What is the expected behavior?**
All toolbar options should be disabled

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
all 5.x versions are affected - works in 4.x though
tested in Chrome, Brave, Firefox 

Maybe refers to https://github.com/tinymce/tinymce/issues/3787

TinyMCE-Fiddle-Brave-2020-01-20-13-56-31

### LINKED ISSUE #5500: Disabling unseen buttons does not work.
**What is the current behavior? Describe the bug**
If the editor is loaded on a page which is not wide enough to show all the buttons in the toolbar, it is set as readonly, and then the page is widened, the buttons that become visible are not disabled.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Open up an editor in a window narrow enough that the "More..."-button becomes visible.
Run tinymce.activeEditor.setMode("readonly") in the web console.
Expand the window to show previously unseen buttons. These will not be disabled and can be used freely.

**What is the expected behavior?**
The behavior I'd expect would be for these buttons to be disabled.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
5.2, Firefox.

### PR DESCRIPTION
**Pull request by wonderbugtiny**
When the toolbar mode is set to anything other than the default(wrap), the toolbar buttons weren't being disabled on read-only mode.  This is now fixed.

Fixes #5356 & fixes #5500

### CODE REVIEW

File: modules/tinymce/src/themes/silver/main/ts/ui/toolbar/button/ToolbarButtons.ts [hunk 1]
```diff
@@ -29,6 +29,7 @@ import { createTieredDataFrom } from '../../menus/menu/SingleMenu';
 import { ToolbarButtonClasses } from '../button/ButtonClasses';
 import { onToolbarButtonExecute, toolbarButtonEventOrder } from '../button/ButtonEvents';
 import { renderToolbarGroup, ToolbarGroup } from '../CommonToolbar';
+import ReadOnly from 'tinymce/themes/silver/ReadOnly';
```
Comment (lnewson) [inline modules/tinymce/src/themes/silver/main/ts/ui/toolbar/button/ToolbarButtons.ts]: This should be a relative import path as its inside the same theme and not from core.

File: modules/tinymce/src/themes/silver/main/ts/ReadOnly.ts [hunk 2]
```diff
@@ -75,17 +64,22 @@ export const setupReadonlyModeSwitch = (editor: Editor, uiComponents: RenderUiCo
...
-          });
+        onReceive(comp, data: ReadOnlyData) {
+          Disabling.set(comp, data.readonly);
         }
       }
     }
   });
 };
+
+export default {
```
Comment (lnewson) [inline modules/tinymce/src/themes/silver/main/ts/ReadOnly.ts]: Default exports are an antipattern and prevent tree shaking, so we shouldn't be using them outside public APIs.

- [ ] Remove default export

**Comment by lnewson** [comment]
It'd also be good to have a test to ensure this works/doesn't regress. You could start the editor in readonly mode at a certain size and then resize it larger and make sure the toolbar buttons are still disabled.

- [ ] Consider adding a test case for this

File: modules/tinymce/src/themes/silver/main/ts/ui/toolbar/button/ToolbarButtons.ts [hunk 3]
```diff
@@ -328,7 +330,8 @@ const renderSplitButton = (spec: Toolbar.ToolbarSplitButton, sharedBackstage: Ui
     onItemExecute: (a, b, c) => { },
 
     splitDropdownBehaviours: Behaviour.derive([
-      DisablingConfigs.splitButton(false),
+      DisablingConfigs.splitButton(false || sharedBackstage.providers.isReadonly()),
```
Comment (lnewson) [inline modules/tinymce/src/themes/silver/main/ts/ui/toolbar/button/ToolbarButtons.ts]: This doesn't make sense, why are you doing `false || sharedBackstage.providers.isReadonly()`? As false will never match so this could just be `sharedBackstage.providers.isReadonly()`.

- [ ] Remove `false` as it doesn't do anything

File: modules/oxide/src/less/theme/components/collection/collection.less [hunk 4]
```diff
@@ -157,7 +157,7 @@
     color: @collection-grid-item-label-enabled-text-color;
   }
 
-  .tox-collection--grid .tox-collection__item--active {
+  .tox-collection--grid .tox-collection__item--active:not([aria-disabled=true]) {
```
Comment (lnewson) [inline modules/oxide/src/less/theme/components/collection/collection.less]: Should this be using `:not(.tox-collection__item--state-disabled)` as that's what everything else uses? Also could this be merged in with the following rule?

```
  .tox-collection--grid .tox-collection__item--active:not(.tox-collection__item--state-disabled) {
    color: @collection-grid-item-label-active-text-color;
  }
```
```

File: modules/oxide/src/less/theme/components/form/color.less [hunk 5]
```diff
@@ -29,14 +29,15 @@
...
       box-shadow: none;
       box-sizing: border-box;
-      cursor: pointer;
       height: @textfield-height - 12px;
       position: absolute;
       top: 6px;
       width: $height;
 
-      &:focus {
+      &:hover:not([aria-disabled=true]),
```
Comment (lnewson) [inline modules/oxide/src/less/theme/components/form/color.less]: Should we be using a class here instead of relying on this attribute?

File: modules/tinymce/src/themes/silver/main/ts/ReadOnly.ts [hunk 6]
```diff
@@ -60,32 +49,37 @@ export const toggleToReadOnly = (uiComponents: RenderUiComponents, readonly: boo
   });
 };
 
-export const setupReadonlyModeSwitch = (editor: Editor, uiComponents: RenderUiComponents) => {
+const setupReadonlyModeSwitch = (editor: Editor, uiComponents: RenderUiComponents) => {
   editor.on('init', () => {
     // Force an update of the ui components disabled states if in readonly mode
-    if (editor.mode.isReadOnly()) {
+    if (editor.readonly) {
```
Comment (lnewson) [inline modules/tinymce/src/themes/silver/main/ts/ReadOnly.ts]: Why was this changed back to `editor.readonly`? @jhaines specifically went through and made all these `editor.mode.isReadonly()` in a previous PR, as it's the definitive API for finding out if the editor is in readonly mode.

- [ ] Consider reverting this change

File: modules/tinymce/src/themes/silver/main/ts/ReadOnly.ts [hunk 7]
```diff
@@ -60,32 +49,37 @@ export const toggleToReadOnly = (uiComponents: RenderUiComponents, readonly: boo
...
       toggleToReadOnly(uiComponents, true);
     }
   });
 
-  editor.on('SwitchMode', () => toggleToReadOnly(uiComponents, editor.mode.isReadOnly()));
+  editor.on('SwitchMode', () => toggleToReadOnly(uiComponents, editor.readonly));
```
Comment (lnewson) [inline modules/tinymce/src/themes/silver/main/ts/ReadOnly.ts]: Another place that was changed to `editor.readonly` that possibly shouldn't have been changed?

File: modules/tinymce/src/themes/silver/main/ts/backstage/Backstage.ts [hunk 8]
```diff
@@ -61,7 +62,8 @@ const init = (sink: AlloyComponent, editor: Editor, lazyAnchorbar: () => AlloyCo
       providers: {
         icons: () => editor.ui.registry.getAll().icons,
         menuItems: () => editor.ui.registry.getAll().menuItems,
-        translate: I18n.translate
+        translate: I18n.translate,
+        isReadonly: () => editor.readonly
```
Comment (lnewson) [inline modules/tinymce/src/themes/silver/main/ts/backstage/Backstage.ts]: This possibly should be `isReadonly: editor.mode.isReadonly` since it's what's used elsewhere?

File: modules/tinymce/src/themes/silver/main/ts/ui/dialog/ColorInput.ts [hunk 9]
```diff
@@ -23,6 +23,7 @@ import {
   SimpleSpec,
   Tabstopping,
   AlloyComponent,
+  Disabling,
```
Comment (lnewson) [inline modules/tinymce/src/themes/silver/main/ts/ui/dialog/ColorInput.ts]: There's a trailing comma that probably shouldn't be there as this is the last item in the import list.

File: modules/tinymce/src/themes/silver/main/ts/ui/dialog/Collection.ts [hunk 10]
```diff
@@ -113,6 +118,18 @@ export const renderCollection = (spec: CollectionSpec, providersBackstage: UiFac
     components: [ ],
     factory: { sketch: Fun.identity },
     behaviours: Behaviour.derive([
+      Disabling.config({
+        disabled: providersBackstage.isReadonly(),
+        onDisabled: (comp) => {
+          Arr.map(SelectorFilter.descendants(comp.element(), '.tox-collection__item'), (childElm) => Class.add(childElm, 'tox-collection__item--state-disabled'));
```
Comment (lnewson) [inline modules/tinymce/src/themes/silver/main/ts/ui/dialog/Collection.ts]: I mentioned this IRL, but looks like it was forgotten but there's a lot of duplicate code here that should be pulled out. It's also very inefficient as you're looping over the same nodes twice which isn't needed.

- [ ] Pull iteration function out to remove duplicate code
- [ ] Don't iterate over the child nodes twice to apply the style/attributes

File: modules/tinymce/src/themes/silver/main/ts/ui/toolbar/CommonToolbar.ts [hunk 11]
```diff
@@ -27,10 +28,10 @@ export interface ToolbarSpec {
   onEscape: (comp: AlloyComponent) => Option<boolean>;
   initGroups: ToolbarGroup[];
   attributes?: Record<string, string>;
+  backstage: UiFactoryBackstage;
```
Comment (lnewson) [inline modules/tinymce/src/themes/silver/main/ts/ui/toolbar/CommonToolbar.ts]: You don't need the entire backstage here, so we should only pass through what's needed. In this case that's just the providers.

- [ ] Only pass through what's needed, not the entire backstage

File: modules/tinymce/src/themes/silver/main/ts/ui/toolbar/button/ToolbarButtons.ts [hunk 12]
```diff
@@ -109,6 +110,7 @@ const renderCommonStructure = (icon: Option<string>, text: Option<string>, toolt
     ]),
 
     eventOrder: {
+      [SystemEvents.receive()]: [ 'receiving', 'reflecting' ],
```
Comment (lnewson) [inline modules/tinymce/src/themes/silver/main/ts/ui/toolbar/button/ToolbarButtons.ts]: This seems as though it should probably be in alloy instead of TinyMCE? given they are both default behaviours in alloy so you'd need to specify this in all places which is weird.

- [ ] Consider moving this to Alloy instead

File: modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/ReadonlyToolbarResizeTest.ts [hunk 13]
```diff
@@ -0,0 +1,118 @@
+import { Pipeline, Chain, Log, NamedChain, ApproxStructure, Assertions, StructAssert, Mouse, UiFinder, Guard } from '@ephox/agar';
+import { UnitTest } from '@ephox/bedrock-client';
+import { TinyLoader } from '@ephox/mcagar';
+import SilverTheme from 'tinymce/themes/silver/Theme';
+import { cResizeToPos } from '../../../module/UiChainUtils';
+import { Element, Body } from '@ephox/sugar';
+import Editor from 'tinymce/core/api/Editor';
+
+UnitTest.asynctest('Editor (Silver) Configuration Close test', (success, failure) => {
```
Comment (lnewson) [inline modules/tinymce/src/themes/silver/test/ts/browser/editor/toolbar/ReadonlyToolbarResizeTest.ts]: This name looks to be incorrect? as it's not related to what's happening in the test.

- [ ] Make sure test name is correct

File: modules/tinymce/src/themes/silver/main/ts/ui/dialog/Collection.ts [hunk 14]
```diff
@@ -60,7 +61,9 @@ export const renderCollection = (spec: CollectionSpec, providersBackstage: UiFac
       const ariaLabel = itemText.replace(/\_| \- |\-/g, (match) => {
         return mapItemName[match];
       });
-      return `<div class="tox-collection__item" tabindex="-1" data-collection-item-value="${escapeAttribute(item.value)}" title="${ariaLabel}" aria-label="${ariaLabel}">${iconContent}${textContent}</div>`;
+
+      const readonlyClass = providersBackstage.isReadonly() ? ' tox-collection__item--state-disabled' : '';
```
Comment (lnewson) [inline modules/tinymce/src/themes/silver/main/ts/ui/dialog/Collection.ts]: This probably should be using `DomFactory` or something instead, as this is getting quite messy and has a lot of potential for HTML injection.

File: modules/tinymce/src/themes/silver/main/ts/ui/dialog/Collection.ts (hunk 10 above)
Comment (lnewson) [reply modules/tinymce/src/themes/silver/main/ts/ui/dialog/Collection.ts]: As an example, this could be something like this:
```
onDisabled: (comp) => {
  iterChildItems((childElm) => {
    Class.add(childElm, 'tox-collection__item--state-disabled'));
    Attr.set(childElm, 'aria-disabled', true);
  });
}
```

File: modules/tinymce/src/themes/silver/main/ts/ui/toolbar/CommonToolbar.ts (hunk 11 above)
Comment (wonderbugtiny) [reply modules/tinymce/src/themes/silver/main/ts/ui/toolbar/CommonToolbar.ts]: The entire backstage is being passed through to `partToolbar` and `partMultipleToolbar` in `/modules/tinymce/src/themes/silver/main/ts/Render.ts`. So, I am assuming it is needed?

File: modules/tinymce/src/themes/silver/main/ts/ui/dialog/Collection.ts (hunk 10 above)
Comment (wonderbugtiny) [reply modules/tinymce/src/themes/silver/main/ts/ui/dialog/Collection.ts]: Yes, sorry I forgot to do it. Thanks for pointing it out.

File: modules/oxide/src/less/theme/components/form/color.less (hunk 5 above)
Comment (wonderbugtiny) [reply modules/oxide/src/less/theme/components/form/color.less]: Moving this to a separate ticket

File: modules/oxide/src/less/theme/components/collection/collection.less (hunk 4 above)
Comment (wonderbugtiny) [reply modules/oxide/src/less/theme/components/collection/collection.less]: I have made this change but I have asked @lostkeys if there is any reason why the two rules shouldn't be merged.

File: modules/tinymce/src/themes/silver/main/ts/ui/toolbar/CommonToolbar.ts (hunk 11 above)
Comment (lnewson) [reply modules/tinymce/src/themes/silver/main/ts/ui/toolbar/CommonToolbar.ts]: As discussed on slack, it's not actually required by any of that and it seems someone passed through the backstage to the `OuterContainer` specs previously. I've provided @wonderbugtiny a patch that shows we only need to pass the providers, not the entire backstage.

File: modules/tinymce/src/themes/silver/main/ts/ReadOnly.ts [hunk 15]
```diff
@@ -46,21 +34,9 @@ const broadcastReadonly = (uiComponents: RenderUiComponents, readonly: boolean)
   uiComponents.uiMothership.broadcastOn([ ReadOnlyChannel ], { readonly });
 };
 
-export const toggleToReadOnly = (uiComponents: RenderUiComponents, readonly: boolean) => {
-  const outerContainer = uiComponents.outerContainer;
-
-  broadcastReadonly(uiComponents, readonly);
+const toggleToReadOnly = (uiComponents: RenderUiComponents, readonly: boolean) => broadcastReadonly(uiComponents, readonly);
```
Comment (lnewson) [inline modules/tinymce/src/themes/silver/main/ts/ReadOnly.ts]: This function really isn't needed anymore, we can just call `broadcastReadonly` instead.
